/**
 * Generated by recon-generate.ts — Stagehand browser fallback for report-scale-regression-1-12-49-e2e-test-15615.
 * Core invokes this automatically when executeHttp throws HttpSchemaError or
 * HttpBotChallengeError. Update the flow steps and extract schema as needed.
 *
 * Steps whose instruction named a labeled payload field have their recon
 * constant spliced to `payload.<field>` so the caller's real value reaches
 * the page; operational-default steps stay literal. The steps run through the
 * self-heal cascade via runHealingFlow — the same engine the recon CLI uses,
 * minus its disk-dump/replan layer.
 */

import type { Stagehand } from "@browserbasehq/stagehand";

import { buildAnthropicClient, buildRephraseModel } from "@enricai/barnacle/lib/llm/anthropic-client";
import { getLogger } from "@enricai/barnacle/lib/logging";
import { type HealingFlowStep, runHealingFlow } from "@enricai/barnacle/scraper/flow-runner";
import { waitForSpaReady } from "@enricai/barnacle/scraper/spa-readiness";
import { guardedExtract } from "@enricai/barnacle/scraper/stagehand-guard";
import type { SessionProxyTuple } from "@enricai/barnacle/types/session-proxy";
import { type ReportScaleRegression11249E2eTest15615Payload, type ReportScaleRegression11249E2eTest15615Response, ReportScaleRegression11249E2eTest15615ResponseSchema } from "@/sites/report-scale-regression-1-12-49-e2e-test-15615/contract";

const logger = getLogger({ name: "report-scale-regression-1-12-49-e2e-test-15615-browser-flow" });

/**
 * Drives report-scale-regression-1-12-49-e2e-test-15615 through the recon flow and extracts structured data. This is
 * the browser path; if contract.ts also defines executeHttp, that hot path runs
 * first and this is the fallback — otherwise this IS the production path.
 */
export async function runReportScaleRegression11249E2eTest15615BrowserFlow(
  stagehand: Stagehand,
  baseUrl: string,
  payload: ReportScaleRegression11249E2eTest15615Payload,
  sessionProxy: SessionProxyTuple | null
): Promise<ReportScaleRegression11249E2eTest15615Response> {
  const page = await stagehand.context.awaitActivePage();

  await page.goto(baseUrl, { waitUntil: "networkidle" });
  // networkidle can resolve before a bot-managed/CDN-fronted SPA hydrates; wait for
  // the real DOM so the first steps don't probe an empty shell page and skip.
  await waitForSpaReady(page, logger);

  const FLOW_STEPS: HealingFlowStep[] = [
  { instruction: "accept cookie banner", optional: false, upload: false, submitStep: false },
  { instruction: "dismiss promo prompt", optional: false, upload: false, submitStep: false },
  { instruction: "poll session ping", optional: false, upload: false, submitStep: false },
  { instruction: "expand facet filters", optional: false, upload: false, submitStep: false },
  { instruction: "browse paged directory listing", optional: false, upload: false, submitStep: false },
  { instruction: "sort listing by relevance", optional: false, upload: false, submitStep: false },
  { instruction: "select first listed record", optional: false, upload: false, submitStep: false },
  { instruction: "open record drill panel", optional: false, upload: false, submitStep: false },
  { instruction: "drill into record variant availability", optional: false, upload: false, submitStep: true },
  { instruction: "confirm variant result summary", optional: false, upload: false, submitStep: false },
  ];

  // buildAnthropicClient() feeds the judge techniques and is null on a
  // Bedrock-only deployment; buildRephraseModel() feeds attempt-5's rephrase
  // and resolves to the Bedrock-backed model in that case, so the cascade
  // keeps full rephrase parity regardless of deployment shape.
  await runHealingFlow({
    stagehand,
    page,
    steps: FLOW_STEPS,
    logger,
    anthropic: buildAnthropicClient(),
    rephraseModel: buildRephraseModel(),
    uploadFixture: null,
    sessionProxy,
  });

  // Schema-enforced extract via guardedExtract: Stagehand 3.4.0 accepts
  // both Zod v3 and v4 schemas natively (StagehandZodSchema union since
  // 2.4.3 / PR #944), and the caller-side safeParse defends against SDK
  // contract drift.
  const result = await guardedExtract(
    stagehand,
    `extract results matching query: ${payload.query}`,
    ReportScaleRegression11249E2eTest15615ResponseSchema
  );

  return result;
}
