/**
 * Generated by recon-generate.ts — review before shipping.
 */

import Bottleneck from "bottleneck";
import { z } from "zod/v4";

import { createHttpClient } from "@enricai/barnacle/scraper/http-client";
import type { BrowserSession } from "@enricai/barnacle/scraper/session";
import type { SitePlugin, SitePluginContext, SitePluginResult } from "@enricai/barnacle/site-plugin";
import { runCombinedVerificationHooksE2eTest101141BrowserFlow } from "@/sites/combined-verification-hooks-e2e-test101141/flows/browser-flow";

const BASE_HEADERS: Record<string, string> = {
  "Content-Type": "application/json",
  Accept: "application/json, */*",
  "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
};

// Safe ceiling: 5 rps — DEFAULT (no rate-limit probe data; run recon:http).
const limiter = new Bottleneck({ minTime: 200 });

export const CombinedVerificationHooksE2eTest101141ResponseSchema = z.object({
  results: z.array(z.object({
    itemId: z.string(),
    meta: z.object({
      storeCurrency: z.string(),
    }).loose(),
    specialOfferEnabled: z.boolean(),
  }).loose()),
}).loose();

export type CombinedVerificationHooksE2eTest101141Response = z.infer<typeof CombinedVerificationHooksE2eTest101141ResponseSchema>;

export default CombinedVerificationHooksE2eTest101141ResponseSchema;

const CombinedVerificationHooksE2eTest101141PayloadSchema = z.object({}).extend({
  BaseUrl: z.string(),
  storeCurrency: z.string(),
  itemId: z.string(),
  page: z.number(),
  specialOfferEnabled: z.boolean(),
});

export type CombinedVerificationHooksE2eTest101141Payload = z.infer<typeof CombinedVerificationHooksE2eTest101141PayloadSchema>;

/**
 * The SITE's own request shape, as captured during recon — NOT the public
 * /run contract (see CombinedVerificationHooksE2eTest101141PayloadSchema above, which is what the real
 * caller sends). Exported so a builder module can import it as the target
 * shape when translating the standard payload into the site's own request
 * bodies (see recon-generate-payload-schema-mismatch.md's prior
 * hand-fix precedent).
 */
export const CombinedVerificationHooksE2eTest101141InternalRequestReference = z.object({
  storeCurrency: z.string(),
  page: z.number(),
});

const httpClient = createHttpClient({ schema: CombinedVerificationHooksE2eTest101141ResponseSchema, bottleneck: limiter, baseHeaders: BASE_HEADERS });

/**
 * Plugin for combined-verification-hooks-e2e-test101141. Tries the direct-HTTP hot path first; falls back to
 * Stagehand automatically on schema drift or bot challenge.
 */
export const combinedVerificationHooksE2eTest101141Plugin: SitePlugin<CombinedVerificationHooksE2eTest101141Payload, CombinedVerificationHooksE2eTest101141Response> = {
  meta: {
    siteId: "combined-verification-hooks-e2e-test101141",
    bodySchema: CombinedVerificationHooksE2eTest101141PayloadSchema,
    responseSchema: CombinedVerificationHooksE2eTest101141ResponseSchema,
    defaultBaseUrl: "https://www.combined-verification-hooks-e2e-fixture.example.com",
    apiVersion: "1.0.0",
  },

  /** Hot path: direct HTTP — no browser, no LLM tokens. */
  async executeHttp(
    payload: CombinedVerificationHooksE2eTest101141Payload,
    _context: SitePluginContext
  ): Promise<SitePluginResult<CombinedVerificationHooksE2eTest101141Response>> {
    const r0 = (await httpClient(`${payload.BaseUrl}/catalog/search/`, {
      method: "POST",
      headers: { "Origin": `${payload.BaseUrl}`, "Referer": `${payload.BaseUrl}/` }, body: `{"storeCurrency":"${payload.storeCurrency}","page":${payload.page}}`,
      schema: z.object({
  results: z.array(z.object({
    itemId: z.string(),
  }).loose()),
}).loose(),
    })) as Record<string, unknown>;

    const foldItems = (r0 as { results: Record<string, unknown>[] }).results;
    await Promise.allSettled(
      (foldItems).map(async (item) => {
      const r1 = (await httpClient(`${payload.BaseUrl}/catalog/detail/`, {
        method: "POST",
        headers: { "Origin": `${payload.BaseUrl}`, "Referer": `${payload.BaseUrl}/` }, body: `{"itemId":"${item.itemId}"}`,
        schema: z.object({
  itemId: z.string(),
  meta: z.object({
    storeCurrency: z.string(),
  }).loose(),
  specialOfferEnabled: z.boolean(),
}).loose(),
      })) as Record<string, unknown>;
      const specialOfferEnabled = (r1 as { specialOfferEnabled: boolean }).specialOfferEnabled;
      await httpClient(`${payload.BaseUrl}/catalog/submit/`, {
        method: "POST",
        headers: { "Origin": `${payload.BaseUrl}`, "Referer": `${payload.BaseUrl}/` }, body: `{"itemId":"${item.itemId}","storeCurrency":"${payload.storeCurrency}","specialOfferEnabled":${specialOfferEnabled}}`,
        schema: z.object({
  ok: z.boolean(),
}).loose(),
      });
      const foldMatch = r1 as Record<string, unknown>;
      Object.assign(item, Object.fromEntries(Object.entries(foldMatch ?? {}).filter(([k]) => !(k in item))));
      })
    );

    return { data: r0 as unknown as CombinedVerificationHooksE2eTest101141Response };
  },

  /** Browser fallback: Stagehand + Steel — invoked only when hot path fails. */
  async execute(
    payload: CombinedVerificationHooksE2eTest101141Payload,
    session: BrowserSession,
    context: SitePluginContext
  ): Promise<SitePluginResult<CombinedVerificationHooksE2eTest101141Response>> {
    const raw = await runCombinedVerificationHooksE2eTest101141BrowserFlow(session.stagehand, context.baseUrl, payload, session.sessionProxy ?? null);
    return { data: raw as CombinedVerificationHooksE2eTest101141Response };
  },
};

// Out-of-tree loader resolves `m.plugin ?? m.default ?? m` — this named
// alias is what BARNACLE_PLUGINS finds; without it the loader would fall
// through to `m.default` (the response schema above) and 404 at runtime.
export { combinedVerificationHooksE2eTest101141Plugin as plugin };
