/**
 * Generated by recon-generate.ts.
 * Build this package, then point BARNACLE_PLUGINS at the compiled module —
 * no core edits required:
 *
 *   BARNACLE_PLUGINS=./dist/sites/combined-verification-hooks-e2e-test101141/index.js pnpm start
 *
 * The loader resolves `m.plugin ?? m.default ?? m` — the `plugin` alias
 * below is what it finds.
 */

export { combinedVerificationHooksE2eTest101141Plugin, combinedVerificationHooksE2eTest101141Plugin as plugin } from "@/sites/combined-verification-hooks-e2e-test101141/contract";
