/**
 * Generated by recon-generate.ts — Stagehand browser fallback for header-threaded-extraction-cast-test-23404.
 * Core invokes this automatically when executeHttp throws HttpSchemaError or
 * HttpBotChallengeError. Update the flow steps and extract schema as needed.
 *
 * Steps whose instruction named a labeled payload field have their recon
 * constant spliced to `payload.<field>` so the caller's real value reaches
 * the page; operational-default steps stay literal. The steps run through the
 * self-heal cascade via runHealingFlow — the same engine the recon CLI uses,
 * minus its disk-dump/replan layer.
 */

import type { Stagehand } from "@browserbasehq/stagehand";
import { z } from "zod/v4";

import { buildAnthropicClient, buildRephraseModel } from "@enricai/barnacle/lib/llm/anthropic-client";
import { getLogger } from "@enricai/barnacle/lib/logging";
import { type HealingFlowStep, runHealingFlow } from "@enricai/barnacle/scraper/flow-runner";
import { waitForSpaReady } from "@enricai/barnacle/scraper/spa-readiness";
import { guardedExtract } from "@enricai/barnacle/scraper/stagehand-guard";
import type { SessionProxyTuple } from "@enricai/barnacle/types/session-proxy";
import type { HeaderThreadedExtractionCastTest23404Payload, HeaderThreadedExtractionCastTest23404Response } from "@/sites/header-threaded-extraction-cast-test-23404/contract";

const logger = getLogger({ name: "header-threaded-extraction-cast-test-23404-browser-flow" });

const HeaderThreadedExtractionCastTest23404BrowserSchema = z.object({
  // runHealingFlow throws StepVerificationError on a failed submitStep, so
  // reaching this point already proves the submission verified.
  verified: z.boolean(),
});

/**
 * Drives header-threaded-extraction-cast-test-23404 through the recon flow and extracts structured data. This is
 * the browser path; if contract.ts also defines executeHttp, that hot path runs
 * first and this is the fallback — otherwise this IS the production path.
 */
export async function runHeaderThreadedExtractionCastTest23404BrowserFlow(
  stagehand: Stagehand,
  entryUrl: string,
  payload: HeaderThreadedExtractionCastTest23404Payload,
  sessionProxy: SessionProxyTuple | null
): Promise<HeaderThreadedExtractionCastTest23404Response> {
  const page = await stagehand.context.awaitActivePage();

  await page.goto(entryUrl, { waitUntil: "networkidle" });
  // networkidle can resolve before a bot-managed/CDN-fronted SPA hydrates; wait for
  // the real DOM so the first steps don't probe an empty shell page and skip.
  await waitForSpaReady(page, logger);

  const FLOW_STEPS: HealingFlowStep[] = [
  { instruction: "browse catalog search", optional: false, upload: false, submitStep: false },
  { instruction: "open item detail panel", optional: false, upload: false, submitStep: false },
  { instruction: "submit item selection", optional: false, upload: false, submitStep: true },
  ];

  // buildAnthropicClient() feeds the judge techniques and is null on a
  // Bedrock-only deployment; buildRephraseModel() feeds attempt-5's rephrase
  // and resolves to the Bedrock-backed model in that case, so the cascade
  // keeps full rephrase parity regardless of deployment shape.
  await runHealingFlow({
    stagehand,
    page,
    steps: FLOW_STEPS,
    logger,
    anthropic: buildAnthropicClient(),
    rephraseModel: buildRephraseModel(),
    uploadFixture: null,
    sessionProxy,
  });

  // Schema-enforced extract via guardedExtract: Stagehand 3.4.0 accepts
  // both Zod v3 and v4 schemas natively (StagehandZodSchema union since
  // 2.4.3 / PR #944), and the caller-side safeParse defends against SDK
  // contract drift.
  // runHealingFlow above already verified the submit (submitStep:true), so the
  // application is already committed at the ATS. A schema-validation or
  // watchdog-timeout throw from this trailing confirmation extract must not
  // propagate and trigger a duplicate re-dispatch — catch it, log it, and
  // degrade to a not-confirmed result instead.
  try {
    const result = await guardedExtract(
      stagehand,
      "is a submission confirmation shown, and what is its reference number?",
      HeaderThreadedExtractionCastTest23404BrowserSchema
    );
    return { ...result, verified: true } as unknown as HeaderThreadedExtractionCastTest23404Response;
  } catch (error) {
    logger.error(`GuardedExtractError: post-submit confirmation extract failed on an already-verified submit, degrading to not-confirmed: ${error}`);
    return { verified: false } as unknown as HeaderThreadedExtractionCastTest23404Response;
  }
}
