/**
 * Generated by recon-generate.ts — review before shipping.
 */

import Bottleneck from "bottleneck";
import { z } from "zod/v4";

import { createHttpClient } from "@enricai/barnacle/scraper/http-client";
import type { BrowserSession } from "@enricai/barnacle/scraper/session";
import type { SitePlugin, SitePluginContext, SitePluginResult } from "@enricai/barnacle/site-plugin";
import { runNonApplicantSubmissionE2eTest23419BrowserFlow } from "@/sites/non-applicant-submission-e2e-test-23419/flows/browser-flow";

const BASE_HEADERS: Record<string, string> = {
  "Content-Type": "application/json",
  Accept: "application/json, */*",
  "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
};

// Safe ceiling: 5 rps — DEFAULT (no rate-limit probe data; run recon:http).
const limiter = new Bottleneck({ minTime: 200 });

export const NonApplicantSubmissionE2eTest23419ResponseSchema = z.object({
  totalPages: z.number(),
  totalAvailableListings: z.number(),
  products: z.array(z.object({
    bookingId: z.string().optional(),
    status: z.string().optional(),
    productId: z.string(),
  }).loose()),
}).loose();

export type NonApplicantSubmissionE2eTest23419Response = z.infer<typeof NonApplicantSubmissionE2eTest23419ResponseSchema>;

export default NonApplicantSubmissionE2eTest23419ResponseSchema;

const NonApplicantSubmissionE2eTest23419PayloadSchema = z.object({}).extend({
  BaseUrl: z.string(),
  category: z.string(),
  checkIn: z.string(),
  checkOut: z.string(),
  endDate: z.string(),
  guests: z.number(),
  page: z.number(),
  productId: z.string(),
  region: z.string(),
  startDate: z.string(),
  unitId: z.string(),
});

export type NonApplicantSubmissionE2eTest23419Payload = z.infer<typeof NonApplicantSubmissionE2eTest23419PayloadSchema>;

/**
 * The SITE's own request shape, as captured during recon — NOT the public
 * /run contract (see NonApplicantSubmissionE2eTest23419PayloadSchema above, which is what the real
 * caller sends). Exported so a builder module can import it as the target
 * shape when translating the standard payload into the site's own request
 * bodies (see recon-generate-payload-schema-mismatch.md's prior
 * hand-fix precedent).
 */
export const NonApplicantSubmissionE2eTest23419InternalRequestReference = z.array(z.unknown());

const httpClient = createHttpClient({ schema: NonApplicantSubmissionE2eTest23419ResponseSchema, bottleneck: limiter, baseHeaders: BASE_HEADERS });

/**
 * Plugin for non-applicant-submission-e2e-test-23419. Tries the direct-HTTP hot path first; falls back to
 * Stagehand automatically on schema drift or bot challenge.
 */
export const nonApplicantSubmissionE2eTest23419Plugin: SitePlugin<NonApplicantSubmissionE2eTest23419Payload, NonApplicantSubmissionE2eTest23419Response> = {
  meta: {
    siteId: "non-applicant-submission-e2e-test-23419",
    bodySchema: NonApplicantSubmissionE2eTest23419PayloadSchema,
    responseSchema: NonApplicantSubmissionE2eTest23419ResponseSchema,
    defaultBaseUrl: "https://www.own-backend-non-applicant-submission-fixture.example.com",
    apiVersion: "1.0.0",
  },

  /** Hot path: direct HTTP — no browser, no LLM tokens. */
  async executeHttp(
    payload: NonApplicantSubmissionE2eTest23419Payload,
    _context: SitePluginContext
  ): Promise<SitePluginResult<NonApplicantSubmissionE2eTest23419Response>> {
    await httpClient(`${payload.BaseUrl}/listings-avail-spa/toggles/product-avail`, {
      method: "POST",
      headers: { "Origin": `${payload.BaseUrl}`, "Referer": `${payload.BaseUrl}/` }, body: `[]`,
      schema: z.array(z.object({
  name: z.string(),
  enabled: z.boolean(),
}).loose()),
    });

    await httpClient(`${payload.BaseUrl}/listings-avail-api/authz/private`, {
      method: "POST",
      headers: { "Origin": `${payload.BaseUrl}`, "Referer": `${payload.BaseUrl}/` }, body: `{}`,
      schema: z.object({
  result: z.string(),
  successful: z.boolean(),
}).loose(),
    });

    const r2 = (await httpClient(`${payload.BaseUrl}/listings-avail-api/available-products/`, {
      method: "POST",
      headers: { "Origin": `${payload.BaseUrl}`, "Referer": `${payload.BaseUrl}/` }, body: `{"category":"${payload.category}","region":"${payload.region}","page":${payload.page}}`,
      schema: z.object({
  totalPages: z.number(),
  totalAvailableListings: z.number(),
  products: z.array(z.object({
    productId: z.string(),
  }).loose()),
}).loose(),
    })) as Record<string, unknown>;

    const foldItems = (r2 as { products: Record<string, unknown>[] }).products;
    await Promise.allSettled(
      (foldItems).map(async (item) => {
      const r3 = (await httpClient(`${payload.BaseUrl}/listings-avail-api/available-units/`, {
        method: "POST",
        headers: { "Origin": `${payload.BaseUrl}`, "Referer": `${payload.BaseUrl}/` }, body: `{"productId":"${item.productId}","startDate":"${payload.startDate}","endDate":"${payload.endDate}"}`,
        schema: z.object({
  units: z.array(z.object({
    unitId: z.string(),
  }).loose()),
  exchangeRate: z.number(),
}).loose(),
      })) as Record<string, unknown>;
      const unitId = (r3 as { units: { "0": { unitId: string } } }).units["0"].unitId;
      const r4 = (await httpClient(`${payload.BaseUrl}/listings-avail-api/book-availability/`, {
        method: "POST",
        headers: { "Origin": `${payload.BaseUrl}`, "Referer": `${payload.BaseUrl}/` }, body: `{"unitId":"${unitId}","checkIn":"${payload.checkIn}","checkOut":"${payload.checkOut}","guests":${payload.guests}}`,
        schema: z.object({
  bookingId: z.string(),
  status: z.string(),
}).loose(),
      })) as Record<string, unknown>;
      const foldMatch = r4 as Record<string, unknown>;
      Object.assign(item, Object.fromEntries(Object.entries(foldMatch ?? {}).filter(([k]) => !(k in item))));
      })
    );

    return { data: r2 as unknown as NonApplicantSubmissionE2eTest23419Response };
  },

  /** Browser fallback: Stagehand + Steel — invoked only when hot path fails. */
  async execute(
    payload: NonApplicantSubmissionE2eTest23419Payload,
    session: BrowserSession,
    context: SitePluginContext
  ): Promise<SitePluginResult<NonApplicantSubmissionE2eTest23419Response>> {
    const raw = await runNonApplicantSubmissionE2eTest23419BrowserFlow(session.stagehand, context.baseUrl, payload, session.sessionProxy ?? null);
    return { data: raw as NonApplicantSubmissionE2eTest23419Response };
  },
};

// Out-of-tree loader resolves `m.plugin ?? m.default ?? m` — this named
// alias is what BARNACLE_PLUGINS finds; without it the loader would fall
// through to `m.default` (the response schema above) and 404 at runtime.
export { nonApplicantSubmissionE2eTest23419Plugin as plugin };
