/**
 * Generated by recon-generate.ts.
 * Build this package, then point BARNACLE_PLUGINS at the compiled module —
 * no core edits required:
 *
 *   BARNACLE_PLUGINS=./dist/sites/non-applicant-submission-e2e-test-23419/index.js pnpm start
 *
 * The loader resolves `m.plugin ?? m.default ?? m` — the `plugin` alias
 * below is what it finds.
 */

export { nonApplicantSubmissionE2eTest23419Plugin, nonApplicantSubmissionE2eTest23419Plugin as plugin } from "@/sites/non-applicant-submission-e2e-test-23419/contract";
