/**
 * Generated by recon-generate.ts — Stagehand browser fallback for recon-primary-op-provenance-e2e-test-23558.
 * Core invokes this automatically when executeHttp throws HttpSchemaError or
 * HttpBotChallengeError. Update the flow steps and extract schema as needed.
 *
 * Steps whose instruction named a labeled payload field have their recon
 * constant spliced to `payload.<field>` so the caller's real value reaches
 * the page; operational-default steps stay literal. The steps run through the
 * self-heal cascade via runHealingFlow — the same engine the recon CLI uses,
 * minus its disk-dump/replan layer.
 */

import type { Stagehand } from "@browserbasehq/stagehand";

import { buildAnthropicClient, buildRephraseModel } from "@enricai/barnacle/lib/llm/anthropic-client";
import { getLogger } from "@enricai/barnacle/lib/logging";
import { type HealingFlowStep, runHealingFlow } from "@enricai/barnacle/scraper/flow-runner";
import { waitForSpaReady } from "@enricai/barnacle/scraper/spa-readiness";
import { guardedExtract } from "@enricai/barnacle/scraper/stagehand-guard";
import type { SessionProxyTuple } from "@enricai/barnacle/types/session-proxy";
import { type ReconPrimaryOpProvenanceE2eTest23558Payload, type ReconPrimaryOpProvenanceE2eTest23558Response, ReconPrimaryOpProvenanceE2eTest23558ResponseSchema } from "@/sites/recon-primary-op-provenance-e2e-test-23558/contract";

const logger = getLogger({ name: "recon-primary-op-provenance-e2e-test-23558-browser-flow" });

/**
 * Drives recon-primary-op-provenance-e2e-test-23558 through the recon flow and extracts structured data. This is
 * the browser path; if contract.ts also defines executeHttp, that hot path runs
 * first and this is the fallback — otherwise this IS the production path.
 */
export async function runReconPrimaryOpProvenanceE2eTest23558BrowserFlow(
  stagehand: Stagehand,
  baseUrl: string,
  payload: ReconPrimaryOpProvenanceE2eTest23558Payload,
  sessionProxy: SessionProxyTuple | null
): Promise<ReconPrimaryOpProvenanceE2eTest23558Response> {
  const page = await stagehand.context.awaitActivePage();

  await page.goto(baseUrl, { waitUntil: "networkidle" });
  // networkidle can resolve before a bot-managed/CDN-fronted SPA hydrates; wait for
  // the real DOM so the first steps don't probe an empty shell page and skip.
  await waitForSpaReady(page, logger);

  const FLOW_STEPS: HealingFlowStep[] = [
  { instruction: `select ${payload.category} from the Category dropdown`, optional: false, upload: false, submitStep: false },
  ];

  // buildAnthropicClient() feeds the judge techniques and is null on a
  // Bedrock-only deployment; buildRephraseModel() feeds attempt-5's rephrase
  // and resolves to the Bedrock-backed model in that case, so the cascade
  // keeps full rephrase parity regardless of deployment shape.
  await runHealingFlow({
    stagehand,
    page,
    steps: FLOW_STEPS,
    logger,
    anthropic: buildAnthropicClient(),
    rephraseModel: buildRephraseModel(),
    uploadFixture: null,
    sessionProxy,
  });

  // Schema-enforced extract via guardedExtract: Stagehand 3.4.0 accepts
  // both Zod v3 and v4 schemas natively (StagehandZodSchema union since
  // 2.4.3 / PR #944), and the caller-side safeParse defends against SDK
  // contract drift.
  const result = await guardedExtract(
    stagehand,
    `extract results matching query: ${payload.query}`,
    ReconPrimaryOpProvenanceE2eTest23558ResponseSchema
  );

  return result;
}
