/**
 * Generated by recon-generate.ts — review before shipping.
 */

import Bottleneck from "bottleneck";
import { z } from "zod/v4";

import { createHttpClient } from "@enricai/barnacle/scraper/http-client";
import type { BrowserSession } from "@enricai/barnacle/scraper/session";
import type { SitePlugin, SitePluginContext, SitePluginResult } from "@enricai/barnacle/site-plugin";
import { runPayloadFieldBodySchemaStructuralParityE2eTest101149BrowserFlow } from "@/sites/payload-field-body-schema-structural-parity-e2e-test101149/flows/browser-flow";

const BASE_HEADERS: Record<string, string> = {
  "Content-Type": "application/json",
  Accept: "application/json, */*",
  "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
};

// Safe ceiling: 5 rps — DEFAULT (no rate-limit probe data; run recon:http).
const limiter = new Bottleneck({ minTime: 200 });

export const PayloadFieldBodySchemaStructuralParityE2eTest101149ResponseSchema = z.object({
  totalPages: z.number(),
  results: z.array(z.object({
    ok: z.boolean().optional(),
    storeCode: z.string(),
    itemId: z.string(),
  }).loose()),
}).loose();

export type PayloadFieldBodySchemaStructuralParityE2eTest101149Response = z.infer<typeof PayloadFieldBodySchemaStructuralParityE2eTest101149ResponseSchema>;

export default PayloadFieldBodySchemaStructuralParityE2eTest101149ResponseSchema;

const PayloadFieldBodySchemaStructuralParityE2eTest101149PayloadSchema = z.object({}).extend({
  BaseUrl: z.string(),
  exploreMorePage: z.string(),
  currency: z.string(),
  itemId: z.enum(["item-a", "item-b", "item-c"]),
  page: z.string(),
  region: z.string(),
  storeId: z.string(),
});

export type PayloadFieldBodySchemaStructuralParityE2eTest101149Payload = z.infer<typeof PayloadFieldBodySchemaStructuralParityE2eTest101149PayloadSchema>;

/**
 * The SITE's own request shape, as captured during recon — NOT the public
 * /run contract (see PayloadFieldBodySchemaStructuralParityE2eTest101149PayloadSchema above, which is what the real
 * caller sends). Exported so a builder module can import it as the target
 * shape when translating the standard payload into the site's own request
 * bodies (see recon-generate-payload-schema-mismatch.md's prior
 * hand-fix precedent).
 */
export const PayloadFieldBodySchemaStructuralParityE2eTest101149InternalRequestReference = z.object({
  itemId: z.string(),
  exploreMorePage: z.string(),
});

const httpClient = createHttpClient({ schema: PayloadFieldBodySchemaStructuralParityE2eTest101149ResponseSchema, bottleneck: limiter, baseHeaders: BASE_HEADERS });

/**
 * Plugin for payload-field-body-schema-structural-parity-e2e-test101149. Tries the direct-HTTP hot path first; falls back to
 * Stagehand automatically on schema drift or bot challenge.
 */
export const payloadFieldBodySchemaStructuralParityE2eTest101149Plugin: SitePlugin<PayloadFieldBodySchemaStructuralParityE2eTest101149Payload, PayloadFieldBodySchemaStructuralParityE2eTest101149Response> = {
  meta: {
    siteId: "payload-field-body-schema-structural-parity-e2e-test101149",
    bodySchema: PayloadFieldBodySchemaStructuralParityE2eTest101149PayloadSchema,
    responseSchema: PayloadFieldBodySchemaStructuralParityE2eTest101149ResponseSchema,
    defaultBaseUrl: "https://www.payload-field-body-schema-structural-parity-fixture.example.com",
    apiVersion: "1.0.0",
  },

  /** Hot path: direct HTTP — no browser, no LLM tokens. */
  async executeHttp(
    payload: PayloadFieldBodySchemaStructuralParityE2eTest101149Payload,
    _context: SitePluginContext
  ): Promise<SitePluginResult<PayloadFieldBodySchemaStructuralParityE2eTest101149Response>> {
    const r0 = (await httpClient(`${payload.BaseUrl}/catalog/search/`, {
      method: "POST",
      headers: { "Origin": `${payload.BaseUrl}`, "Referer": `${payload.BaseUrl}/` }, body: `{"page":"${payload.exploreMorePage}","storeId":"${payload.storeId}","region":"${payload.region}","currency":"${payload.currency}"}`,
      schema: z.object({
  totalPages: z.number(),
  results: z.array(z.object({
    itemId: z.string(),
  }).loose()),
}).loose(),
    })) as Record<string, unknown>;

    const foldItems = (r0 as { results: Record<string, unknown>[] }).results;
    await Promise.allSettled(
      (foldItems).map(async (item) => {
      const r1 = (await httpClient(`${payload.BaseUrl}/catalog/detail/`, {
        method: "POST",
        headers: { "Origin": `${payload.BaseUrl}`, "Referer": `${payload.BaseUrl}/` }, body: `{"itemId":"${item.itemId}","exploreMorePage":"${payload.exploreMorePage}"}`,
        schema: z.object({
  storeCode: z.string(),
}).loose(),
      })) as Record<string, unknown>;
      const foldMatch0 = r1 as Record<string, unknown>;
      Object.assign(item, Object.fromEntries(Object.entries(foldMatch0 ?? {}).filter(([k]) => !(k in item))));
      const r4 = (await httpClient(`${payload.BaseUrl}/catalog/submit/`, {
        method: "POST",
        headers: { "Origin": `${payload.BaseUrl}`, "Referer": `${payload.BaseUrl}/` }, body: `{"itemId":"${item.itemId}","page":"${payload.exploreMorePage}","storeId":"${payload.storeId}","region":"${payload.region}","currency":"${payload.currency}"}`,
        schema: z.object({
  ok: z.boolean(),
}).loose(),
      })) as Record<string, unknown>;
      const foldMatch1 = r4 as Record<string, unknown>;
      Object.assign(item, Object.fromEntries(Object.entries(foldMatch1 ?? {}).filter(([k]) => !(k in item))));
      })
    );

    return { data: r0 as unknown as PayloadFieldBodySchemaStructuralParityE2eTest101149Response };
  },

  /** Browser fallback: Stagehand + Steel — invoked only when hot path fails. */
  async execute(
    payload: PayloadFieldBodySchemaStructuralParityE2eTest101149Payload,
    session: BrowserSession,
    context: SitePluginContext
  ): Promise<SitePluginResult<PayloadFieldBodySchemaStructuralParityE2eTest101149Response>> {
    const raw = await runPayloadFieldBodySchemaStructuralParityE2eTest101149BrowserFlow(session.stagehand, context.baseUrl, payload, session.sessionProxy ?? null);
    return { data: raw as PayloadFieldBodySchemaStructuralParityE2eTest101149Response };
  },
};

// Out-of-tree loader resolves `m.plugin ?? m.default ?? m` — this named
// alias is what BARNACLE_PLUGINS finds; without it the loader would fall
// through to `m.default` (the response schema above) and 404 at runtime.
export { payloadFieldBodySchemaStructuralParityE2eTest101149Plugin as plugin };
