/**
 * Generated by recon-generate.ts.
 * Build this package, then point BARNACLE_PLUGINS at the compiled module —
 * no core edits required:
 *
 *   BARNACLE_PLUGINS=./dist/sites/payload-field-body-schema-structural-parity-e2e-test101149/index.js pnpm start
 *
 * The loader resolves `m.plugin ?? m.default ?? m` — the `plugin` alias
 * below is what it finds.
 */

export { payloadFieldBodySchemaStructuralParityE2eTest101149Plugin, payloadFieldBodySchemaStructuralParityE2eTest101149Plugin as plugin } from "@/sites/payload-field-body-schema-structural-parity-e2e-test101149/contract";
