/**
 * Generated by recon-generate.ts — review before shipping.
 */

import Bottleneck from "bottleneck";
import { z } from "zod/v4";

import { createHttpClient } from "@enricai/barnacle/scraper/http-client";
import type { BrowserSession } from "@enricai/barnacle/scraper/session";
import type { SitePlugin, SitePluginContext, SitePluginResult } from "@enricai/barnacle/site-plugin";
import { runHeaderThreadedExtractionCastTest23404BrowserFlow } from "@/sites/header-threaded-extraction-cast-test-23404/flows/browser-flow";

const BASE_HEADERS: Record<string, string> = {
  "Content-Type": "application/json",
  Accept: "application/json, */*",
  "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
  Authorization: "true",
};

// Safe ceiling: 5 rps — DEFAULT (no rate-limit probe data; run recon:http).
const limiter = new Bottleneck({ minTime: 200 });

export const HeaderThreadedExtractionCastTest23404ResponseSchema = z.object({
  results: z.array(z.object({
    sessionCode: z.string(),
    authorization: z.boolean(),
    itemId: z.string(),
  }).loose()),
}).loose();

export type HeaderThreadedExtractionCastTest23404Response = z.infer<typeof HeaderThreadedExtractionCastTest23404ResponseSchema>;

export default HeaderThreadedExtractionCastTest23404ResponseSchema;

const HeaderThreadedExtractionCastTest23404PayloadSchema = z.object({}).extend({
  BaseUrl: z.string(),
  itemId: z.string(),
  page: z.number(),
  sessionCode: z.string(),
});

export type HeaderThreadedExtractionCastTest23404Payload = z.infer<typeof HeaderThreadedExtractionCastTest23404PayloadSchema>;

/**
 * The SITE's own request shape, as captured during recon — NOT the public
 * /run contract (see HeaderThreadedExtractionCastTest23404PayloadSchema above, which is what the real
 * caller sends). Exported so a builder module can import it as the target
 * shape when translating the standard payload into the site's own request
 * bodies (see recon-generate-payload-schema-mismatch.md's prior
 * hand-fix precedent).
 */
export const HeaderThreadedExtractionCastTest23404InternalRequestReference = z.object({
  page: z.number(),
});

const httpClient = createHttpClient({ schema: HeaderThreadedExtractionCastTest23404ResponseSchema, bottleneck: limiter, baseHeaders: BASE_HEADERS });

/**
 * Plugin for header-threaded-extraction-cast-test-23404. Tries the direct-HTTP hot path first; falls back to
 * Stagehand automatically on schema drift or bot challenge.
 */
export const headerThreadedExtractionCastTest23404Plugin: SitePlugin<HeaderThreadedExtractionCastTest23404Payload, HeaderThreadedExtractionCastTest23404Response> = {
  meta: {
    siteId: "header-threaded-extraction-cast-test-23404",
    bodySchema: HeaderThreadedExtractionCastTest23404PayloadSchema,
    responseSchema: HeaderThreadedExtractionCastTest23404ResponseSchema,
    defaultBaseUrl: "https://www.header-threaded-extraction-cast-fixture.example.com",
    apiVersion: "1.0.0",
  },

  /** Hot path: direct HTTP — no browser, no LLM tokens. */
  async executeHttp(
    payload: HeaderThreadedExtractionCastTest23404Payload,
    _context: SitePluginContext
  ): Promise<SitePluginResult<HeaderThreadedExtractionCastTest23404Response>> {
    const r0 = (await httpClient(`${payload.BaseUrl}/catalog/search/`, {
      method: "POST",
      headers: { "Origin": `${payload.BaseUrl}`, "Referer": `${payload.BaseUrl}/` }, body: `{"page":${payload.page}}`,
      schema: z.object({
  results: z.array(z.object({
    itemId: z.string(),
  }).loose()),
}).loose(),
    })) as Record<string, unknown>;

    const foldItems = (r0 as { results: Record<string, unknown>[] }).results;
    await Promise.allSettled(
      (foldItems).map(async (item) => {
      const r1 = (await httpClient(`${payload.BaseUrl}/catalog/detail/`, {
        method: "POST",
        headers: { "Origin": `${payload.BaseUrl}`, "Referer": `${payload.BaseUrl}/` }, body: `{"itemId":"${item.itemId}"}`,
        schema: z.object({
  sessionCode: z.string(),
  authorization: z.boolean(),
}).loose(),
      })) as Record<string, unknown>;
      const authorization = (r1 as { authorization: boolean }).authorization;
      const r2 = (await httpClient(`${payload.BaseUrl}/catalog/submit/`, {
        method: "POST",
        headers: { "Authorization": `${authorization}`, "Origin": `${payload.BaseUrl}`, "Referer": `${payload.BaseUrl}/` }, body: `{"itemId":"${item.itemId}","sessionCode":"${payload.sessionCode}"}`,
        schema: z.object({
  ok: z.boolean(),
}).loose(),
      })) as Record<string, unknown>;
      const foldMatch = r1 as Record<string, unknown>;
      Object.assign(item, Object.fromEntries(Object.entries(foldMatch ?? {}).filter(([k]) => !(k in item))));
      })
    );

    return { data: r0 as unknown as HeaderThreadedExtractionCastTest23404Response };
  },

  /** Browser fallback: Stagehand + Steel — invoked only when hot path fails. */
  async execute(
    payload: HeaderThreadedExtractionCastTest23404Payload,
    session: BrowserSession,
    context: SitePluginContext
  ): Promise<SitePluginResult<HeaderThreadedExtractionCastTest23404Response>> {
    const raw = await runHeaderThreadedExtractionCastTest23404BrowserFlow(session.stagehand, context.baseUrl, payload, session.sessionProxy ?? null);
    return { data: raw as HeaderThreadedExtractionCastTest23404Response };
  },
};

// Out-of-tree loader resolves `m.plugin ?? m.default ?? m` — this named
// alias is what BARNACLE_PLUGINS finds; without it the loader would fall
// through to `m.default` (the response schema above) and 404 at runtime.
export { headerThreadedExtractionCastTest23404Plugin as plugin };
