/**
 * Generated by recon-generate.ts.
 * Build this package, then point BARNACLE_PLUGINS at the compiled module —
 * no core edits required:
 *
 *   BARNACLE_PLUGINS=./dist/sites/header-threaded-extraction-cast-test-23404/index.js pnpm start
 *
 * The loader resolves `m.plugin ?? m.default ?? m` — the `plugin` alias
 * below is what it finds.
 */

export { headerThreadedExtractionCastTest23404Plugin, headerThreadedExtractionCastTest23404Plugin as plugin } from "@/sites/header-threaded-extraction-cast-test-23404/contract";
