/**
 * Generated by recon-generate.ts — Stagehand browser fallback for gql-navigateto-array-element-optional-facet-splice-test-119059.
 * Core invokes this automatically when executeHttp throws HttpSchemaError or
 * HttpBotChallengeError. Update the flow steps and extract schema as needed.
 *
 * Steps whose instruction named a labeled payload field have their recon
 * constant spliced to `payload.<field>` so the caller's real value reaches
 * the page; operational-default steps stay literal. The steps run through the
 * self-heal cascade via runHealingFlow — the same engine the recon CLI uses,
 * minus its disk-dump/replan layer.
 */

import type { Stagehand } from "@browserbasehq/stagehand";

import { buildAnthropicClient, buildRephraseModel } from "@enricai/barnacle/lib/llm/anthropic-client";
import { getLogger } from "@enricai/barnacle/lib/logging";
import { type HealingFlowStep, runHealingFlow } from "@enricai/barnacle/scraper/flow-runner";
import { waitForSpaReady } from "@enricai/barnacle/scraper/spa-readiness";
import { guardedExtract } from "@enricai/barnacle/scraper/stagehand-guard";
import type { SessionProxyTuple } from "@enricai/barnacle/types/session-proxy";
import { type GqlNavigatetoArrayElementOptionalFacetSpliceTest119059Payload, type GqlNavigatetoArrayElementOptionalFacetSpliceTest119059Response, GqlNavigatetoArrayElementOptionalFacetSpliceTest119059ResponseSchema } from "@/sites/gql-navigateto-array-element-optional-facet-splice-test-119059/contract";

const logger = getLogger({ name: "gql-navigateto-array-element-optional-facet-splice-test-119059-browser-flow" });

/**
 * Drives gql-navigateto-array-element-optional-facet-splice-test-119059 through the recon flow and extracts structured data. This is
 * the browser path; if contract.ts also defines executeHttp, that hot path runs
 * first and this is the fallback — otherwise this IS the production path.
 */
export async function runGqlNavigatetoArrayElementOptionalFacetSpliceTest119059BrowserFlow(
  stagehand: Stagehand,
  baseUrl: string,
  payload: GqlNavigatetoArrayElementOptionalFacetSpliceTest119059Payload,
  sessionProxy: SessionProxyTuple | null
): Promise<GqlNavigatetoArrayElementOptionalFacetSpliceTest119059Response> {
  const page = await stagehand.context.awaitActivePage();

  await page.goto(baseUrl, { waitUntil: "networkidle" });
  // networkidle can resolve before a bot-managed/CDN-fronted SPA hydrates; wait for
  // the real DOM so the first steps don't probe an empty shell page and skip.
  await waitForSpaReady(page, logger);

  const FLOW_STEPS: HealingFlowStep[] = [
  { instruction: "navigate to the catalog with the category facet applied", optional: false, upload: false, submitStep: false, navigateTo: "https://www.gql-navigateto-array-element-optional-facet-splice-fixture.example.com/#/catalog/catx-gql-array-facet-hash-7712" },
  { instruction: "navigate to the catalog with the brand facet applied", optional: true, upload: false, submitStep: false, navigateTo: "https://www.gql-navigateto-array-element-optional-facet-splice-fixture.example.com/#/catalog/brandx-gql-array-facet-hash-5583" },
  { instruction: "browse catalog", optional: false, upload: false, submitStep: false },
  ];

  // buildAnthropicClient() feeds the judge techniques and is null on a
  // Bedrock-only deployment; buildRephraseModel() feeds attempt-5's rephrase
  // and resolves to the Bedrock-backed model in that case, so the cascade
  // keeps full rephrase parity regardless of deployment shape.
  await runHealingFlow({
    stagehand,
    page,
    steps: FLOW_STEPS,
    logger,
    anthropic: buildAnthropicClient(),
    rephraseModel: buildRephraseModel(),
    uploadFixture: null,
    sessionProxy,
  });

  // Schema-enforced extract via guardedExtract: Stagehand 3.4.0 accepts
  // both Zod v3 and v4 schemas natively (StagehandZodSchema union since
  // 2.4.3 / PR #944), and the caller-side safeParse defends against SDK
  // contract drift.
  const result = await guardedExtract(
    stagehand,
    `extract results matching query: ${payload.query}`,
    GqlNavigatetoArrayElementOptionalFacetSpliceTest119059ResponseSchema
  );

  return result;
}
