/**
 * Generated by recon-generate.ts — review before shipping.
 */

import Bottleneck from "bottleneck";
import { z } from "zod/v4";

import { createGraphqlClient } from "@enricai/barnacle/scraper/graphql-client";
import type { BrowserSession } from "@enricai/barnacle/scraper/session";
import type { SitePlugin, SitePluginContext, SitePluginResult } from "@enricai/barnacle/site-plugin";
import { runReconPrimaryOpProvenanceE2eTest23558BrowserFlow } from "@/sites/recon-primary-op-provenance-e2e-test-23558/flows/browser-flow";

const BASE_HEADERS: Record<string, string> = {
  "Content-Type": "application/json",
  Accept: "application/json, */*",
  Origin: "https://shop.example.com",
  Referer: "https://shop.example.com/",
  "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
};

// Safe ceiling: 5 rps — DEFAULT (no rate-limit probe data; run recon:http).
const limiter = new Bottleneck({ minTime: 200 });

export const ReconPrimaryOpProvenanceE2eTest23558ResponseSchema = z.object({
  results: z.array(z.object({
    id: z.string(),
    name: z.string(),
  }).loose()),
}).loose();

export type ReconPrimaryOpProvenanceE2eTest23558Response = z.infer<typeof ReconPrimaryOpProvenanceE2eTest23558ResponseSchema>;

export default ReconPrimaryOpProvenanceE2eTest23558ResponseSchema;

const ReconPrimaryOpProvenanceE2eTest23558PayloadSchema = z.object({
  query: z.string().min(1),
}).extend({
  category: z.string(),
});

export type ReconPrimaryOpProvenanceE2eTest23558Payload = z.infer<typeof ReconPrimaryOpProvenanceE2eTest23558PayloadSchema>;

// Lifted verbatim from recon capture. The adjacent response schema is drift-tolerant by construction (dropped __typename, .loose() objects), so this query text is not hand-trimmed.
const RECONPRIMARYOPPROVENANCEE2ETEST23558_QUERY = `query SearchResults($filters: String) { results(filters: $filters) { id name } }`;

type GqlFn = (operationName: string, query: string, variables: Record<string, unknown>) => Promise<ReconPrimaryOpProvenanceE2eTest23558Response>;

const gqlCache = new Map<string, GqlFn>();

function getGql(baseUrl: string): GqlFn {
  let client = gqlCache.get(baseUrl);
  if (!client) {
    client = createGraphqlClient({
      schema: ReconPrimaryOpProvenanceE2eTest23558ResponseSchema,
      bottleneck: limiter,
      baseHeaders: BASE_HEADERS,
      endpoint: `${baseUrl}/graphql`,
    });
    gqlCache.set(baseUrl, client);
  }
  return client;
}

/**
 * Plugin for recon-primary-op-provenance-e2e-test-23558. Tries the direct-HTTP hot path first; falls back to
 * Stagehand automatically on schema drift or bot challenge.
 */
export const reconPrimaryOpProvenanceE2eTest23558Plugin: SitePlugin<ReconPrimaryOpProvenanceE2eTest23558Payload, ReconPrimaryOpProvenanceE2eTest23558Response> = {
  meta: {
    siteId: "recon-primary-op-provenance-e2e-test-23558",
    bodySchema: ReconPrimaryOpProvenanceE2eTest23558PayloadSchema,
    responseSchema: ReconPrimaryOpProvenanceE2eTest23558ResponseSchema,
    defaultBaseUrl: "https://shop.example.com",
    apiVersion: "1.0.0",
  },

  /** Hot path: direct HTTP — no browser, no LLM tokens. */
  async executeHttp(
    payload: ReconPrimaryOpProvenanceE2eTest23558Payload,
    context: SitePluginContext
  ): Promise<SitePluginResult<ReconPrimaryOpProvenanceE2eTest23558Response>> {
    const data = await getGql(context.baseUrl)("SearchResults", RECONPRIMARYOPPROVENANCEE2ETEST23558_QUERY, { filters: `category:${payload.category}` });
    return { data };
  },

  /** Browser fallback: Stagehand + Steel — invoked only when hot path fails. */
  async execute(
    payload: ReconPrimaryOpProvenanceE2eTest23558Payload,
    session: BrowserSession,
    context: SitePluginContext
  ): Promise<SitePluginResult<ReconPrimaryOpProvenanceE2eTest23558Response>> {
    const raw = await runReconPrimaryOpProvenanceE2eTest23558BrowserFlow(session.stagehand, context.baseUrl, payload, session.sessionProxy ?? null);
    return { data: raw as ReconPrimaryOpProvenanceE2eTest23558Response };
  },
};

// Out-of-tree loader resolves `m.plugin ?? m.default ?? m` — this named
// alias is what BARNACLE_PLUGINS finds; without it the loader would fall
// through to `m.default` (the response schema above) and 404 at runtime.
export { reconPrimaryOpProvenanceE2eTest23558Plugin as plugin };
