/**
 * Generated by recon-generate.ts.
 * Build this package, then point BARNACLE_PLUGINS at the compiled module —
 * no core edits required:
 *
 *   BARNACLE_PLUGINS=./dist/sites/recon-primary-op-provenance-e2e-test-23558/index.js pnpm start
 *
 * The loader resolves `m.plugin ?? m.default ?? m` — the `plugin` alias
 * below is what it finds.
 */

export { reconPrimaryOpProvenanceE2eTest23558Plugin, reconPrimaryOpProvenanceE2eTest23558Plugin as plugin } from "@/sites/recon-primary-op-provenance-e2e-test-23558/contract";
