/**
 * Generated by recon-generate.ts — review before shipping.
 */

import Bottleneck from "bottleneck";
import { z } from "zod/v4";

import { createGraphqlClient } from "@enricai/barnacle/scraper/graphql-client";
import type { BrowserSession } from "@enricai/barnacle/scraper/session";
import type { SitePlugin, SitePluginContext, SitePluginResult } from "@enricai/barnacle/site-plugin";
import { runGqlNavigatetoArrayElementOptionalFacetSpliceTest119059BrowserFlow } from "@/sites/gql-navigateto-array-element-optional-facet-splice-test-119059/flows/browser-flow";

const BASE_HEADERS: Record<string, string> = {
  "Content-Type": "application/json",
  Accept: "application/json, */*",
  Origin: "https://www.gql-navigateto-array-element-optional-facet-splice-fixture.example.com",
  Referer: "https://www.gql-navigateto-array-element-optional-facet-splice-fixture.example.com/",
  "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
};

// Safe ceiling: 5 rps — DEFAULT (no rate-limit probe data; run recon:http).
const limiter = new Bottleneck({ minTime: 200 });

export const GqlNavigatetoArrayElementOptionalFacetSpliceTest119059ResponseSchema = z.object({
  products: z.array(z.object({
    id: z.string(),
  }).loose()),
}).loose();

export type GqlNavigatetoArrayElementOptionalFacetSpliceTest119059Response = z.infer<typeof GqlNavigatetoArrayElementOptionalFacetSpliceTest119059ResponseSchema>;

export default GqlNavigatetoArrayElementOptionalFacetSpliceTest119059ResponseSchema;

const GqlNavigatetoArrayElementOptionalFacetSpliceTest119059PayloadSchema = z.object({
  query: z.string().min(1),
}).extend({
  BrandFacet: z.string(),
  CategoryFacet: z.string(),
});

export type GqlNavigatetoArrayElementOptionalFacetSpliceTest119059Payload = z.infer<typeof GqlNavigatetoArrayElementOptionalFacetSpliceTest119059PayloadSchema>;

// Lifted verbatim from recon capture. The adjacent response schema is drift-tolerant by construction (dropped __typename, .loose() objects), so this query text is not hand-trimmed.
const GQLNAVIGATETOARRAYELEMENTOPTIONALFACETSPLICETEST119059_QUERY = `query catalogSearch_Products($sort: SortInput, $filters: [String!]) { products(sort: $sort, filters: $filters) { id } }`;

type GqlFn = (operationName: string, query: string, variables: Record<string, unknown>) => Promise<GqlNavigatetoArrayElementOptionalFacetSpliceTest119059Response>;

const gqlCache = new Map<string, GqlFn>();

function getGql(baseUrl: string): GqlFn {
  let client = gqlCache.get(baseUrl);
  if (!client) {
    client = createGraphqlClient({
      schema: GqlNavigatetoArrayElementOptionalFacetSpliceTest119059ResponseSchema,
      bottleneck: limiter,
      baseHeaders: BASE_HEADERS,
      endpoint: `${baseUrl}/graphql`,
    });
    gqlCache.set(baseUrl, client);
  }
  return client;
}

/**
 * Plugin for gql-navigateto-array-element-optional-facet-splice-test-119059. Tries the direct-HTTP hot path first; falls back to
 * Stagehand automatically on schema drift or bot challenge.
 */
export const gqlNavigatetoArrayElementOptionalFacetSpliceTest119059Plugin: SitePlugin<GqlNavigatetoArrayElementOptionalFacetSpliceTest119059Payload, GqlNavigatetoArrayElementOptionalFacetSpliceTest119059Response> = {
  meta: {
    siteId: "gql-navigateto-array-element-optional-facet-splice-test-119059",
    bodySchema: GqlNavigatetoArrayElementOptionalFacetSpliceTest119059PayloadSchema,
    responseSchema: GqlNavigatetoArrayElementOptionalFacetSpliceTest119059ResponseSchema,
    defaultBaseUrl: "https://www.gql-navigateto-array-element-optional-facet-splice-fixture.example.com",
    apiVersion: "1.0.0",
  },

  /** Hot path: direct HTTP — no browser, no LLM tokens. */
  async executeHttp(
    payload: GqlNavigatetoArrayElementOptionalFacetSpliceTest119059Payload,
    context: SitePluginContext
  ): Promise<SitePluginResult<GqlNavigatetoArrayElementOptionalFacetSpliceTest119059Response>> {
    const data = await getGql(context.baseUrl)("catalogSearch_Products", GQLNAVIGATETOARRAYELEMENTOPTIONALFACETSPLICETEST119059_QUERY, { sort: { by: "RECOMMENDED" }, filters: [`${payload.CategoryFacet};filterId=urlFriendlyId`, "evergreen-item", ...(payload.BrandFacet ? [`${payload.BrandFacet};filterId=urlFriendlyId`] : [])] });
    return { data };
  },

  /** Browser fallback: Stagehand + Steel — invoked only when hot path fails. */
  async execute(
    payload: GqlNavigatetoArrayElementOptionalFacetSpliceTest119059Payload,
    session: BrowserSession,
    context: SitePluginContext
  ): Promise<SitePluginResult<GqlNavigatetoArrayElementOptionalFacetSpliceTest119059Response>> {
    const raw = await runGqlNavigatetoArrayElementOptionalFacetSpliceTest119059BrowserFlow(session.stagehand, context.baseUrl, payload, session.sessionProxy ?? null);
    return { data: raw as GqlNavigatetoArrayElementOptionalFacetSpliceTest119059Response };
  },
};

// Out-of-tree loader resolves `m.plugin ?? m.default ?? m` — this named
// alias is what BARNACLE_PLUGINS finds; without it the loader would fall
// through to `m.default` (the response schema above) and 404 at runtime.
export { gqlNavigatetoArrayElementOptionalFacetSpliceTest119059Plugin as plugin };
