/**
 * Generated by recon-generate.ts.
 * Build this package, then point BARNACLE_PLUGINS at the compiled module —
 * no core edits required:
 *
 *   BARNACLE_PLUGINS=./dist/sites/gql-navigateto-array-element-optional-facet-splice-test-119059/index.js pnpm start
 *
 * The loader resolves `m.plugin ?? m.default ?? m` — the `plugin` alias
 * below is what it finds.
 */

export { gqlNavigatetoArrayElementOptionalFacetSpliceTest119059Plugin, gqlNavigatetoArrayElementOptionalFacetSpliceTest119059Plugin as plugin } from "@/sites/gql-navigateto-array-element-optional-facet-splice-test-119059/contract";
