/**
 * Runtime helper for loading committed static JSON fixtures captured during
 * the recon playbook (Step 3B — auxiliary endpoints). Use this instead of
 * re-fetching static reference data (markets, currencies, labels, etc.) on
 * every production call — these fixtures are cheap memory reads and should
 * be re-generated by re-running recon when drift is detected.
 */

import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import type { z } from "zod";

/**
 * Loads a committed JSON fixture from the `sites/<siteId>/fixtures/<filename>`
 * directory alongside the running module and validates it with the provided Zod
 * schema. Throws on missing file or schema mismatch — both indicate the fixture
 * is stale and recon needs re-running.
 *
 * Path is resolved relative to `__dirname` so it works in both environments:
 * - Dev (`tsx src/scraper/fixtures.ts`): `__dirname` = `src/scraper/`,
 *   resolves to `src/sites/<id>/fixtures/<filename>`.
 * - Prod (`node dist/scraper/fixtures.js`): `__dirname` = `dist/scraper/`,
 *   resolves to `dist/sites/<id>/fixtures/<filename>` — which `pnpm run build`
 *   populates by copying `src/sites/` to `dist/sites/`.
 */
export function loadFixture<T>(siteId: string, filename: string, schema: z.ZodType<T>): T {
  const fixturePath = resolve(__dirname, "..", "sites", siteId, "fixtures", filename);
  let raw: string;
  try {
    raw = readFileSync(fixturePath, "utf8");
  } catch {
    throw new Error(
      `fixture not found: ${fixturePath} — run recon-http.ts and commit the output to src/sites/${siteId}/fixtures/${filename}`
    );
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    throw new Error(`fixture is not valid JSON: ${fixturePath}`);
  }

  const result = schema.safeParse(parsed);
  if (!result.success) {
    throw new Error(
      `fixture schema mismatch: ${fixturePath} — re-run recon-http.ts to refresh. Issues: ${JSON.stringify(result.error.issues)}`
    );
  }

  return result.data;
}
