/**
 * Generated by recon-generate.ts — review before shipping.
 */

import Bottleneck from "bottleneck";
import { z } from "zod/v4";

import { createGraphqlClient } from "@enricai/barnacle/scraper/graphql-client";
import type { BrowserSession } from "@enricai/barnacle/scraper/session";
import type { SitePlugin, SitePluginContext, SitePluginResult } from "@enricai/barnacle/site-plugin";
import { runFirstGraphqlCapturePrimaryHostNarrowingE2eTest118843BrowserFlow } from "@/sites/first-graphql-capture-primary-host-narrowing-e2e-test-118843/flows/browser-flow";

const BASE_HEADERS: Record<string, string> = {
  "Content-Type": "application/json",
  Accept: "application/json, */*",
  Origin: "https://catalog.fallback-narrowing-fixture.example.com",
  Referer: "https://catalog.fallback-narrowing-fixture.example.com/",
  "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
};

// Safe ceiling: 5 rps — DEFAULT (no rate-limit probe data; run recon:http).
const limiter = new Bottleneck({ minTime: 200 });

export const FirstGraphqlCapturePrimaryHostNarrowingE2eTest118843ResponseSchema = z.object({
  results: z.array(z.object({
    id: z.string(),
    name: z.string(),
  }).loose()),
}).loose();

export type FirstGraphqlCapturePrimaryHostNarrowingE2eTest118843Response = z.infer<typeof FirstGraphqlCapturePrimaryHostNarrowingE2eTest118843ResponseSchema>;

export default FirstGraphqlCapturePrimaryHostNarrowingE2eTest118843ResponseSchema;

const FirstGraphqlCapturePrimaryHostNarrowingE2eTest118843PayloadSchema = z.object({
  query: z.string().min(1),
}).extend({
  category: z.string(),
});

export type FirstGraphqlCapturePrimaryHostNarrowingE2eTest118843Payload = z.infer<typeof FirstGraphqlCapturePrimaryHostNarrowingE2eTest118843PayloadSchema>;

// Lifted verbatim from recon capture. The adjacent response schema is drift-tolerant by construction (dropped __typename, .loose() objects), so this query text is not hand-trimmed.
const FIRSTGRAPHQLCAPTUREPRIMARYHOSTNARROWINGE2ETEST118843_QUERY = `query SearchResults($filters: String) { results(filters: $filters) { id name } }`;

type GqlFn = (operationName: string, query: string, variables: Record<string, unknown>) => Promise<FirstGraphqlCapturePrimaryHostNarrowingE2eTest118843Response>;

const gqlCache = new Map<string, GqlFn>();

function getGql(baseUrl: string): GqlFn {
  let client = gqlCache.get(baseUrl);
  if (!client) {
    client = createGraphqlClient({
      schema: FirstGraphqlCapturePrimaryHostNarrowingE2eTest118843ResponseSchema,
      bottleneck: limiter,
      baseHeaders: BASE_HEADERS,
      endpoint: `${baseUrl}/graphql`,
    });
    gqlCache.set(baseUrl, client);
  }
  return client;
}

/**
 * Plugin for first-graphql-capture-primary-host-narrowing-e2e-test-118843. Tries the direct-HTTP hot path first; falls back to
 * Stagehand automatically on schema drift or bot challenge.
 */
export const firstGraphqlCapturePrimaryHostNarrowingE2eTest118843Plugin: SitePlugin<FirstGraphqlCapturePrimaryHostNarrowingE2eTest118843Payload, FirstGraphqlCapturePrimaryHostNarrowingE2eTest118843Response> = {
  meta: {
    siteId: "first-graphql-capture-primary-host-narrowing-e2e-test-118843",
    bodySchema: FirstGraphqlCapturePrimaryHostNarrowingE2eTest118843PayloadSchema,
    responseSchema: FirstGraphqlCapturePrimaryHostNarrowingE2eTest118843ResponseSchema,
    defaultBaseUrl: "https://catalog.fallback-narrowing-fixture.example.com",
    apiVersion: "1.0.0",
  },

  /** Hot path: direct HTTP — no browser, no LLM tokens. */
  async executeHttp(
    _payload: FirstGraphqlCapturePrimaryHostNarrowingE2eTest118843Payload,
    context: SitePluginContext
  ): Promise<SitePluginResult<FirstGraphqlCapturePrimaryHostNarrowingE2eTest118843Response>> {
    const data = await getGql(context.baseUrl)("SearchResults", FIRSTGRAPHQLCAPTUREPRIMARYHOSTNARROWINGE2ETEST118843_QUERY, {});
    return { data };
  },

  /** Browser fallback: Stagehand + Steel — invoked only when hot path fails. */
  async execute(
    payload: FirstGraphqlCapturePrimaryHostNarrowingE2eTest118843Payload,
    session: BrowserSession,
    context: SitePluginContext
  ): Promise<SitePluginResult<FirstGraphqlCapturePrimaryHostNarrowingE2eTest118843Response>> {
    const raw = await runFirstGraphqlCapturePrimaryHostNarrowingE2eTest118843BrowserFlow(session.stagehand, context.baseUrl, payload, session.sessionProxy ?? null);
    return { data: raw as FirstGraphqlCapturePrimaryHostNarrowingE2eTest118843Response };
  },
};

// Out-of-tree loader resolves `m.plugin ?? m.default ?? m` — this named
// alias is what BARNACLE_PLUGINS finds; without it the loader would fall
// through to `m.default` (the response schema above) and 404 at runtime.
export { firstGraphqlCapturePrimaryHostNarrowingE2eTest118843Plugin as plugin };
