/**
 * Generated by recon-generate.ts.
 * Build this package, then point BARNACLE_PLUGINS at the compiled module —
 * no core edits required:
 *
 *   BARNACLE_PLUGINS=./dist/sites/first-graphql-capture-primary-host-narrowing-e2e-test-118843/index.js pnpm start
 *
 * The loader resolves `m.plugin ?? m.default ?? m` — the `plugin` alias
 * below is what it finds.
 */

export { firstGraphqlCapturePrimaryHostNarrowingE2eTest118843Plugin, firstGraphqlCapturePrimaryHostNarrowingE2eTest118843Plugin as plugin } from "@/sites/first-graphql-capture-primary-host-narrowing-e2e-test-118843/contract";
