/**
 * Generated by recon-generate.ts — review before shipping.
 */

import Bottleneck from "bottleneck";
import { z } from "zod/v4";

import { createHttpClient } from "@enricai/barnacle/scraper/http-client";
import type { BrowserSession } from "@enricai/barnacle/scraper/session";
import type { SitePlugin, SitePluginContext, SitePluginResult } from "@enricai/barnacle/site-plugin";
import { runSubmitpatternFoldreturnChainE2eTest23539BrowserFlow } from "@/sites/submitpattern-foldreturn-chain-e2e-test-23539/flows/browser-flow";

const BASE_HEADERS: Record<string, string> = {
  "Content-Type": "application/json",
  Accept: "application/json, */*",
  "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
};

// Safe ceiling: 5 rps — DEFAULT (no rate-limit probe data; run recon:http).
const limiter = new Bottleneck({ minTime: 200 });

export const SubmitpatternFoldreturnChainE2eTest23539ResponseSchema = z.object({
  totalPages: z.number(),
  totalAvailableListings: z.number(),
  products: z.array(z.object({
    unitId: z.string().optional(),
    price: z.number().optional(),
    productId: z.string(),
  }).loose()),
}).loose();

export type SubmitpatternFoldreturnChainE2eTest23539Response = z.infer<typeof SubmitpatternFoldreturnChainE2eTest23539ResponseSchema>;

export default SubmitpatternFoldreturnChainE2eTest23539ResponseSchema;

const SubmitpatternFoldreturnChainE2eTest23539PayloadSchema = z.object({}).extend({
  BaseUrl: z.string(),
  page: z.number(),
  productId: z.string(),
});

export type SubmitpatternFoldreturnChainE2eTest23539Payload = z.infer<typeof SubmitpatternFoldreturnChainE2eTest23539PayloadSchema>;

/**
 * The SITE's own request shape, as captured during recon — NOT the public
 * /run contract (see SubmitpatternFoldreturnChainE2eTest23539PayloadSchema above, which is what the real
 * caller sends). Exported so a builder module can import it as the target
 * shape when translating the standard payload into the site's own request
 * bodies (see recon-generate-payload-schema-mismatch.md's prior
 * hand-fix precedent).
 */
export const SubmitpatternFoldreturnChainE2eTest23539InternalRequestReference = z.array(z.unknown());

const httpClient = createHttpClient({ schema: SubmitpatternFoldreturnChainE2eTest23539ResponseSchema, bottleneck: limiter, baseHeaders: BASE_HEADERS });

/**
 * Plugin for submitpattern-foldreturn-chain-e2e-test-23539. Tries the direct-HTTP hot path first; falls back to
 * Stagehand automatically on schema drift or bot challenge.
 */
export const submitpatternFoldreturnChainE2eTest23539Plugin: SitePlugin<SubmitpatternFoldreturnChainE2eTest23539Payload, SubmitpatternFoldreturnChainE2eTest23539Response> = {
  meta: {
    siteId: "submitpattern-foldreturn-chain-e2e-test-23539",
    bodySchema: SubmitpatternFoldreturnChainE2eTest23539PayloadSchema,
    responseSchema: SubmitpatternFoldreturnChainE2eTest23539ResponseSchema,
    defaultBaseUrl: "https://www.own-backend-submitpattern-foldreturn-chain-fixture.example.com",
    apiVersion: "1.0.0",
  },

  /** Hot path: direct HTTP — no browser, no LLM tokens. */
  async executeHttp(
    payload: SubmitpatternFoldreturnChainE2eTest23539Payload,
    _context: SitePluginContext
  ): Promise<SitePluginResult<SubmitpatternFoldreturnChainE2eTest23539Response>> {
    await httpClient(`${payload.BaseUrl}/listings-avail-spa/toggles/product-avail`, {
      method: "POST",
      headers: { "Origin": `${payload.BaseUrl}`, "Referer": `${payload.BaseUrl}/` }, body: `[]`,
      schema: z.array(z.object({
  name: z.string(),
  enabled: z.boolean(),
}).loose()),
    });

    await httpClient(`${payload.BaseUrl}/listings-avail-api/authz/private`, {
      method: "POST",
      headers: { "Origin": `${payload.BaseUrl}`, "Referer": `${payload.BaseUrl}/` }, body: `{}`,
      schema: z.object({
  result: z.string(),
  successful: z.boolean(),
}).loose(),
    });

    const r2 = (await httpClient(`${payload.BaseUrl}/listings-avail-api/available-products/`, {
      method: "POST",
      headers: { "Origin": `${payload.BaseUrl}`, "Referer": `${payload.BaseUrl}/` }, body: `{"page":${payload.page}}`,
      schema: z.object({
  totalPages: z.number(),
  totalAvailableListings: z.number(),
  products: z.array(z.object({
    productId: z.string(),
  }).loose()),
}).loose(),
    })) as Record<string, unknown>;

    const foldItems = (r2 as { products: Record<string, unknown>[] }).products;
    await Promise.allSettled(
      (foldItems).map(async (item) => {
      const r3 = (await httpClient(`${payload.BaseUrl}/listings-avail-api/available-units/`, {
        method: "POST",
        headers: { "Origin": `${payload.BaseUrl}`, "Referer": `${payload.BaseUrl}/` }, body: `{"productId":"${item.productId}"}`,
        schema: z.object({
  units: z.array(z.object({
    unitId: z.string(),
  }).loose()),
  exchangeRate: z.number(),
}).loose(),
      })) as Record<string, unknown>;
      const foldMatches0 = (r3 as { units: Record<string, unknown>[] }).units;
      const foldMatch0 = foldMatches0.length === 1 && foldMatches0[0]?.["productId"] === undefined ? foldMatches0[0] : foldMatches0.find((m) => String(m["productId"]) === String(item.productId));
      Object.assign(item, Object.fromEntries(Object.entries(foldMatch0 ?? {}).filter(([k]) => !(k in item))));
      const r4 = (await httpClient(`${payload.BaseUrl}/listings-avail-api/available-units-drilldown/`, {
        method: "POST",
        headers: { "Origin": `${payload.BaseUrl}`, "Referer": `${payload.BaseUrl}/` }, body: `{"productId":"${item.productId}"}`,
        schema: z.object({
  drillResults: z.object({
    units: z.array(z.object({
      unitId: z.string(),
      price: z.number(),
    }).loose()),
  }).loose(),
}).loose(),
      })) as Record<string, unknown>;
      const foldMatches1 = (r4 as { drillResults: { units: Record<string, unknown>[] } }).drillResults.units;
      const foldMatch1 = foldMatches1.length === 1 && foldMatches1[0]?.["productId"] === undefined ? foldMatches1[0] : foldMatches1.find((m) => String(m["productId"]) === String(item.productId));
      Object.assign(item, Object.fromEntries(Object.entries(foldMatch1 ?? {}).filter(([k]) => !(k in item))));
      })
    );

    return { data: r2 as unknown as SubmitpatternFoldreturnChainE2eTest23539Response };
  },

  /** Browser fallback: Stagehand + Steel — invoked only when hot path fails. */
  async execute(
    payload: SubmitpatternFoldreturnChainE2eTest23539Payload,
    session: BrowserSession,
    context: SitePluginContext
  ): Promise<SitePluginResult<SubmitpatternFoldreturnChainE2eTest23539Response>> {
    const raw = await runSubmitpatternFoldreturnChainE2eTest23539BrowserFlow(session.stagehand, context.baseUrl, payload, session.sessionProxy ?? null);
    return { data: raw as SubmitpatternFoldreturnChainE2eTest23539Response };
  },
};

// Out-of-tree loader resolves `m.plugin ?? m.default ?? m` — this named
// alias is what BARNACLE_PLUGINS finds; without it the loader would fall
// through to `m.default` (the response schema above) and 404 at runtime.
export { submitpatternFoldreturnChainE2eTest23539Plugin as plugin };
