/**
 * Generated by recon-generate.ts.
 * Build this package, then point BARNACLE_PLUGINS at the compiled module —
 * no core edits required:
 *
 *   BARNACLE_PLUGINS=./dist/sites/submitpattern-foldreturn-chain-e2e-test-23539/index.js pnpm start
 *
 * The loader resolves `m.plugin ?? m.default ?? m` — the `plugin` alias
 * below is what it finds.
 */

export { submitpatternFoldreturnChainE2eTest23539Plugin, submitpatternFoldreturnChainE2eTest23539Plugin as plugin } from "@/sites/submitpattern-foldreturn-chain-e2e-test-23539/contract";
