/**
 * Generated by recon-generate.ts — review before shipping.
 */

import Bottleneck from "bottleneck";
import { z } from "zod/v4";

import { createGraphqlClient } from "@enricai/barnacle/scraper/graphql-client";
import type { BrowserSession } from "@enricai/barnacle/scraper/session";
import type { SitePlugin, SitePluginContext, SitePluginResult } from "@enricai/barnacle/site-plugin";
import { runPaginationNoSiblingTest23565BrowserFlow } from "@/sites/pagination-no-sibling-test-23565/flows/browser-flow";

const BASE_HEADERS: Record<string, string> = {
  "Content-Type": "application/json",
  Accept: "application/json, */*",
  Origin: "https://www.items-fixture.example.com",
  Referer: "https://www.items-fixture.example.com/",
  "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
};

// Safe ceiling: 5 rps — DEFAULT (no rate-limit probe data; run recon:http).
const limiter = new Bottleneck({ minTime: 200 });

export const PaginationNoSiblingTest23565ResponseSchema = z.object({
  search_Items: z.object({
    total: z.number(),
    items: z.array(z.object({
      id: z.string(),
      title: z.string(),
    }).loose()),
  }).loose(),
}).loose();

export type PaginationNoSiblingTest23565Response = z.infer<typeof PaginationNoSiblingTest23565ResponseSchema>;

export default PaginationNoSiblingTest23565ResponseSchema;

const PaginationNoSiblingTest23565PayloadSchema = z.object({
  query: z.string().min(1),
});

export type PaginationNoSiblingTest23565Payload = z.infer<typeof PaginationNoSiblingTest23565PayloadSchema>;

// Lifted verbatim from recon capture. The adjacent response schema is drift-tolerant by construction (dropped __typename, .loose() objects), so this query text is not hand-trimmed.
const PAGINATIONNOSIBLINGTEST23565_QUERY = `query listingSearch_Items($pagination: PaginationInput, $filters: String) { search_Items(pagination: $pagination, filters: $filters) { total items { id title } } }`;

type GqlFn = (operationName: string, query: string, variables: Record<string, unknown>) => Promise<PaginationNoSiblingTest23565Response>;

const gqlCache = new Map<string, GqlFn>();

function getGql(baseUrl: string): GqlFn {
  let client = gqlCache.get(baseUrl);
  if (!client) {
    client = createGraphqlClient({
      schema: PaginationNoSiblingTest23565ResponseSchema,
      bottleneck: limiter,
      baseHeaders: BASE_HEADERS,
      endpoint: `${baseUrl}/items/graph`,
    });
    gqlCache.set(baseUrl, client);
  }
  return client;
}

/**
 * Plugin for pagination-no-sibling-test-23565. Tries the direct-HTTP hot path first; falls back to
 * Stagehand automatically on schema drift or bot challenge.
 */
export const paginationNoSiblingTest23565Plugin: SitePlugin<PaginationNoSiblingTest23565Payload, PaginationNoSiblingTest23565Response> = {
  meta: {
    siteId: "pagination-no-sibling-test-23565",
    bodySchema: PaginationNoSiblingTest23565PayloadSchema,
    responseSchema: PaginationNoSiblingTest23565ResponseSchema,
    defaultBaseUrl: "https://www.items-fixture.example.com",
    apiVersion: "1.0.0",
  },

  /** Hot path: direct HTTP — no browser, no LLM tokens. */
  async executeHttp(
    _payload: PaginationNoSiblingTest23565Payload,
    context: SitePluginContext
  ): Promise<SitePluginResult<PaginationNoSiblingTest23565Response>> {
    const data = await getGql(context.baseUrl)("listingSearch_Items", PAGINATIONNOSIBLINGTEST23565_QUERY, { pagination: {"count":10,"skip":0}, filters: "category:widgets|color:blue" });
    return { data };
  },

  /** Browser fallback: Stagehand + Steel — invoked only when hot path fails. */
  async execute(
    payload: PaginationNoSiblingTest23565Payload,
    session: BrowserSession,
    context: SitePluginContext
  ): Promise<SitePluginResult<PaginationNoSiblingTest23565Response>> {
    const raw = await runPaginationNoSiblingTest23565BrowserFlow(session.stagehand, context.baseUrl, payload, session.sessionProxy ?? null);
    return { data: raw as PaginationNoSiblingTest23565Response };
  },
};

// Out-of-tree loader resolves `m.plugin ?? m.default ?? m` — this named
// alias is what BARNACLE_PLUGINS finds; without it the loader would fall
// through to `m.default` (the response schema above) and 404 at runtime.
export { paginationNoSiblingTest23565Plugin as plugin };
