/**
 * Generated by recon-generate.ts.
 * Build this package, then point BARNACLE_PLUGINS at the compiled module —
 * no core edits required:
 *
 *   BARNACLE_PLUGINS=./dist/sites/pagination-no-sibling-test-23565/index.js pnpm start
 *
 * The loader resolves `m.plugin ?? m.default ?? m` — the `plugin` alias
 * below is what it finds.
 */

export { paginationNoSiblingTest23565Plugin, paginationNoSiblingTest23565Plugin as plugin } from "@/sites/pagination-no-sibling-test-23565/contract";
