/**
 * Generated by recon-generate.ts — review before shipping.
 */

import Bottleneck from "bottleneck";
import { z } from "zod/v4";

import { createHttpClient } from "@enricai/barnacle/scraper/http-client";
import type { BrowserSession } from "@enricai/barnacle/scraper/session";
import type { SitePlugin, SitePluginContext, SitePluginResult } from "@enricai/barnacle/site-plugin";
import { runCustomHeaderExtractionCastTest23366BrowserFlow } from "@/sites/custom-header-extraction-cast-test-23366/flows/browser-flow";

const BASE_HEADERS: Record<string, string> = {
  "Content-Type": "application/json",
  Accept: "application/json, */*",
  "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
  "X-Item-Verified": "true",
};

// Safe ceiling: 5 rps — DEFAULT (no rate-limit probe data; run recon:http).
const limiter = new Bottleneck({ minTime: 200 });

export const CustomHeaderExtractionCastTest23366ResponseSchema = z.object({
  results: z.array(z.object({
    sessionCode: z.string(),
    verified: z.boolean(),
    itemId: z.string(),
    ok: z.boolean().optional(),
  }).loose()),
}).loose();

export type CustomHeaderExtractionCastTest23366Response = z.infer<typeof CustomHeaderExtractionCastTest23366ResponseSchema>;

export default CustomHeaderExtractionCastTest23366ResponseSchema;

const CustomHeaderExtractionCastTest23366PayloadSchema = z.object({}).extend({
  BaseUrl: z.string(),
  itemId: z.enum(["item-a", "item-b"]),
  sessionCode: z.enum(["false", "true"]),
});

export type CustomHeaderExtractionCastTest23366Payload = z.infer<typeof CustomHeaderExtractionCastTest23366PayloadSchema>;

/**
 * The SITE's own request shape, as captured during recon — NOT the public
 * /run contract (see CustomHeaderExtractionCastTest23366PayloadSchema above, which is what the real
 * caller sends). Exported so a builder module can import it as the target
 * shape when translating the standard payload into the site's own request
 * bodies (see recon-generate-payload-schema-mismatch.md's prior
 * hand-fix precedent).
 */
export const CustomHeaderExtractionCastTest23366InternalRequestReference = z.object({
  itemId: z.string(),
});

const httpClient = createHttpClient({ schema: CustomHeaderExtractionCastTest23366ResponseSchema, bottleneck: limiter, baseHeaders: BASE_HEADERS });

/**
 * Plugin for custom-header-extraction-cast-test-23366. Tries the direct-HTTP hot path first; falls back to
 * Stagehand automatically on schema drift or bot challenge.
 */
export const customHeaderExtractionCastTest23366Plugin: SitePlugin<CustomHeaderExtractionCastTest23366Payload, CustomHeaderExtractionCastTest23366Response> = {
  meta: {
    siteId: "custom-header-extraction-cast-test-23366",
    bodySchema: CustomHeaderExtractionCastTest23366PayloadSchema,
    responseSchema: CustomHeaderExtractionCastTest23366ResponseSchema,
    defaultBaseUrl: "https://www.custom-header-extraction-cast-fixture.example.com",
    apiVersion: "1.0.0",
  },

  /** Hot path: direct HTTP — no browser, no LLM tokens. */
  async executeHttp(
    payload: CustomHeaderExtractionCastTest23366Payload,
    _context: SitePluginContext
  ): Promise<SitePluginResult<CustomHeaderExtractionCastTest23366Response>> {
    const r0 = (await httpClient(`${payload.BaseUrl}/catalog/search/`, {
      method: "POST",
      headers: { "Origin": `${payload.BaseUrl}`, "Referer": `${payload.BaseUrl}/` }, body: `{"page":1}`,
      schema: z.object({
  results: z.array(z.object({
    itemId: z.string(),
  }).loose()),
}).loose(),
    })) as Record<string, unknown>;

    const foldItems = (r0 as { results: Record<string, unknown>[] }).results;
    await Promise.allSettled(
      (foldItems).map(async (item) => {
      const r1 = (await httpClient(`${payload.BaseUrl}/catalog/detail/`, {
        method: "POST",
        headers: { "Origin": `${payload.BaseUrl}`, "Referer": `${payload.BaseUrl}/` }, body: `{"itemId":"${item.itemId}"}`,
        schema: z.object({
  sessionCode: z.string(),
  verified: z.boolean(),
}).loose(),
      })) as Record<string, unknown>;
      const verified = (r1 as { verified: boolean }).verified;
      const r2 = (await httpClient(`${payload.BaseUrl}/catalog/submit/`, {
        method: "POST",
        headers: { "X-Item-Verified": `${verified}`, "Origin": `${payload.BaseUrl}`, "Referer": `${payload.BaseUrl}/` }, body: `{"itemId":"${item.itemId}","sessionCode":"${payload.sessionCode}"}`,
        schema: z.object({
  ok: z.boolean(),
}).loose(),
      })) as Record<string, unknown>;
      const foldMatch0 = r1 as Record<string, unknown>;
      Object.assign(item, Object.fromEntries(Object.entries(foldMatch0 ?? {}).filter(([k]) => !(k in item))));
      const r4 = (await httpClient(`${payload.BaseUrl}/catalog/submit/`, {
        method: "POST",
        headers: { "Origin": `${payload.BaseUrl}`, "Referer": `${payload.BaseUrl}/` }, body: `{"itemId":"${item.itemId}","sessionCode":"${payload.sessionCode}"}`,
        schema: z.object({
  ok: z.boolean(),
}).loose(),
      })) as Record<string, unknown>;
      const foldMatch1 = r4 as Record<string, unknown>;
      Object.assign(item, Object.fromEntries(Object.entries(foldMatch1 ?? {}).filter(([k]) => !(k in item))));
      })
    );

    return { data: r0 as unknown as CustomHeaderExtractionCastTest23366Response };
  },

  /** Browser fallback: Stagehand + Steel — invoked only when hot path fails. */
  async execute(
    payload: CustomHeaderExtractionCastTest23366Payload,
    session: BrowserSession,
    context: SitePluginContext
  ): Promise<SitePluginResult<CustomHeaderExtractionCastTest23366Response>> {
    const raw = await runCustomHeaderExtractionCastTest23366BrowserFlow(session.stagehand, context.baseUrl, payload, session.sessionProxy ?? null);
    return { data: raw as CustomHeaderExtractionCastTest23366Response };
  },
};

// Out-of-tree loader resolves `m.plugin ?? m.default ?? m` — this named
// alias is what BARNACLE_PLUGINS finds; without it the loader would fall
// through to `m.default` (the response schema above) and 404 at runtime.
export { customHeaderExtractionCastTest23366Plugin as plugin };
