/**
 * Generated by recon-generate.ts.
 * Build this package, then point BARNACLE_PLUGINS at the compiled module —
 * no core edits required:
 *
 *   BARNACLE_PLUGINS=./dist/sites/custom-header-extraction-cast-test-23366/index.js pnpm start
 *
 * The loader resolves `m.plugin ?? m.default ?? m` — the `plugin` alias
 * below is what it finds.
 */

export { customHeaderExtractionCastTest23366Plugin, customHeaderExtractionCastTest23366Plugin as plugin } from "@/sites/custom-header-extraction-cast-test-23366/contract";
