/**
 * Generated by recon-generate.ts — review before shipping.
 */

import Bottleneck from "bottleneck";
import { z } from "zod/v4";

import { createHttpClient } from "@enricai/barnacle/scraper/http-client";
import type { BrowserSession } from "@enricai/barnacle/scraper/session";
import type { SitePlugin, SitePluginContext, SitePluginResult } from "@enricai/barnacle/site-plugin";
import { runPagedDrillMixed4xxE2eTest23287BrowserFlow } from "@/sites/paged-drill-mixed-4xx-e2e-test-23287/flows/browser-flow";

const BASE_HEADERS: Record<string, string> = {
  "Content-Type": "application/json",
  Accept: "application/json, */*",
  "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
};

// Safe ceiling: 5 rps — DEFAULT (no rate-limit probe data; run recon:http).
const limiter = new Bottleneck({ minTime: 200 });

export const PagedDrillMixed4xxE2eTest23287ResponseSchema = z.object({
  totalPages: z.number(),
  cruises: z.array(z.object({
    id: z.string(),
    amount: z.number().optional(),
  }).loose()),
}).loose();

export type PagedDrillMixed4xxE2eTest23287Response = z.infer<typeof PagedDrillMixed4xxE2eTest23287ResponseSchema>;

export default PagedDrillMixed4xxE2eTest23287ResponseSchema;

const PagedDrillMixed4xxE2eTest23287PayloadSchema = z.object({}).extend({
  BaseUrl: z.string(),
  id: z.enum(["cruise-0", "cruise-1"]),
});

export type PagedDrillMixed4xxE2eTest23287Payload = z.infer<typeof PagedDrillMixed4xxE2eTest23287PayloadSchema>;

/**
 * The SITE's own request shape, as captured during recon — NOT the public
 * /run contract (see PagedDrillMixed4xxE2eTest23287PayloadSchema above, which is what the real
 * caller sends). Exported so a builder module can import it as the target
 * shape when translating the standard payload into the site's own request
 * bodies (see recon-generate-payload-schema-mismatch.md's prior
 * hand-fix precedent).
 */
export const PagedDrillMixed4xxE2eTest23287InternalRequestReference = z.object({
  id: z.string(),
});

const httpClient = createHttpClient({ schema: PagedDrillMixed4xxE2eTest23287ResponseSchema, bottleneck: limiter, baseHeaders: BASE_HEADERS });

/**
 * Plugin for paged-drill-mixed-4xx-e2e-test-23287. Tries the direct-HTTP hot path first; falls back to
 * Stagehand automatically on schema drift or bot challenge.
 */
export const pagedDrillMixed4xxE2eTest23287Plugin: SitePlugin<PagedDrillMixed4xxE2eTest23287Payload, PagedDrillMixed4xxE2eTest23287Response> = {
  meta: {
    siteId: "paged-drill-mixed-4xx-e2e-test-23287",
    bodySchema: PagedDrillMixed4xxE2eTest23287PayloadSchema,
    responseSchema: PagedDrillMixed4xxE2eTest23287ResponseSchema,
    defaultBaseUrl: "https://api.example.com",
    apiVersion: "1.0.0",
  },

  /** Hot path: direct HTTP — no browser, no LLM tokens. */
  async executeHttp(
    payload: PagedDrillMixed4xxE2eTest23287Payload,
    _context: SitePluginContext
  ): Promise<SitePluginResult<PagedDrillMixed4xxE2eTest23287Response>> {
    const r0 = (await httpClient(`${payload.BaseUrl}/catalog-listing-api/listing/`, {
      method: "POST",
      headers: { "Origin": `${payload.BaseUrl}`, "Referer": `${payload.BaseUrl}/` }, body: `{"page":1}`,
      schema: z.object({
  totalPages: z.number(),
  cruises: z.array(z.object({
    id: z.string(),
  }).loose()),
}).loose(),
    })) as Record<string, unknown>;
    const id2 = (r0 as { cruises: { "1": { id: string } } }).cruises["1"].id;

    const foldItems = (r0 as { cruises: Record<string, unknown>[] }).cruises;
    await Promise.allSettled(
      (foldItems).map(async (item) => {
      const r1 = (await httpClient(`${payload.BaseUrl}/catalog-listing-api/pricing/`, {
        method: "POST",
        headers: { "Origin": `${payload.BaseUrl}`, "Referer": `${payload.BaseUrl}/` }, body: `{"id":"${item.id}"}`,
        schema: z.object({
  prices: z.array(z.object({
    id: z.string(),
    amount: z.number(),
  }).loose()),
}).loose(),
      })) as Record<string, unknown>;
      const foldMatches = (r1 as { prices: Record<string, unknown>[] }).prices;
      const foldMatch = foldMatches.length === 1 && foldMatches[0]?.["id"] === undefined ? foldMatches[0] : foldMatches.find((m) => String(m["id"]) === String(item.id));
      Object.assign(item, Object.fromEntries(Object.entries(foldMatch ?? {}).filter(([k]) => !(k in item))));
      })
    );

    return { data: r0 as unknown as PagedDrillMixed4xxE2eTest23287Response };
  },

  /** Browser fallback: Stagehand + Steel — invoked only when hot path fails. */
  async execute(
    payload: PagedDrillMixed4xxE2eTest23287Payload,
    session: BrowserSession,
    context: SitePluginContext
  ): Promise<SitePluginResult<PagedDrillMixed4xxE2eTest23287Response>> {
    const raw = await runPagedDrillMixed4xxE2eTest23287BrowserFlow(session.stagehand, context.baseUrl, payload, session.sessionProxy ?? null);
    return { data: raw as PagedDrillMixed4xxE2eTest23287Response };
  },
};

// Out-of-tree loader resolves `m.plugin ?? m.default ?? m` — this named
// alias is what BARNACLE_PLUGINS finds; without it the loader would fall
// through to `m.default` (the response schema above) and 404 at runtime.
export { pagedDrillMixed4xxE2eTest23287Plugin as plugin };
