/**
 * Generated by recon-generate.ts.
 * Build this package, then point BARNACLE_PLUGINS at the compiled module —
 * no core edits required:
 *
 *   BARNACLE_PLUGINS=./dist/sites/paged-drill-mixed-4xx-e2e-test-23287/index.js pnpm start
 *
 * The loader resolves `m.plugin ?? m.default ?? m` — the `plugin` alias
 * below is what it finds.
 */

export { pagedDrillMixed4xxE2eTest23287Plugin, pagedDrillMixed4xxE2eTest23287Plugin as plugin } from "@/sites/paged-drill-mixed-4xx-e2e-test-23287/contract";
