/**
 * Generated by recon-generate.ts — review before shipping.
 */

import Bottleneck from "bottleneck";
import { z } from "zod/v4";

import { multipartJsonObject } from "@enricai/barnacle/lib/zod-multipart";
import { createHttpClient } from "@enricai/barnacle/scraper/http-client";
import type { BrowserSession } from "@enricai/barnacle/scraper/session";
import type { SitePlugin, SitePluginContext, SitePluginResult } from "@enricai/barnacle/site-plugin";
import { runArraySchemaBodyParityFacetSpliceTest118863BrowserFlow } from "@/sites/array-schema-body-parity-facet-splice-test-118863/flows/browser-flow";

const BASE_HEADERS: Record<string, string> = {
  "Content-Type": "application/json",
  Accept: "application/json, */*",
  "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
};

// Safe ceiling: 5 rps — DEFAULT (no rate-limit probe data; run recon:http).
const limiter = new Bottleneck({ minTime: 200 });

export const ArraySchemaBodyParityFacetSpliceTest118863ResponseSchema = z.object({
  ok: z.boolean(),
}).loose();

export type ArraySchemaBodyParityFacetSpliceTest118863Response = z.infer<typeof ArraySchemaBodyParityFacetSpliceTest118863ResponseSchema>;

export default ArraySchemaBodyParityFacetSpliceTest118863ResponseSchema;

const ArraySchemaBodyParityFacetSpliceTest118863PayloadSchema = z.object({}).extend({
  BaseUrl: z.string(),
  BrandFacet: z.string(),
  CategoryFacet: z.string(),
  RegionFacet: z.string(),
  page: z.coerce.number(),
  storeRegion: z.string(),
  ordering: multipartJsonObject(z.array(z.object({
  criteria: z.string(),
  order: z.string(),
  region: z.string(),
}))),
  tags: multipartJsonObject(z.array(z.string())),
});

export type ArraySchemaBodyParityFacetSpliceTest118863Payload = z.infer<typeof ArraySchemaBodyParityFacetSpliceTest118863PayloadSchema>;

/**
 * The SITE's own request shape, as captured during recon — NOT the public
 * /run contract (see ArraySchemaBodyParityFacetSpliceTest118863PayloadSchema above, which is what the real
 * caller sends). Exported so a builder module can import it as the target
 * shape when translating the standard payload into the site's own request
 * bodies (see recon-generate-payload-schema-mismatch.md's prior
 * hand-fix precedent).
 */
export const ArraySchemaBodyParityFacetSpliceTest118863InternalRequestReference = z.object({
  ordering: z.array(z.object({
    criteria: z.string(),
    order: z.string(),
    region: z.string(),
  })),
  tags: z.array(z.string()),
});

const httpClient = createHttpClient({ schema: ArraySchemaBodyParityFacetSpliceTest118863ResponseSchema, bottleneck: limiter, baseHeaders: BASE_HEADERS });

/**
 * Plugin for array-schema-body-parity-facet-splice-test-118863. Tries the direct-HTTP hot path first; falls back to
 * Stagehand automatically on schema drift or bot challenge.
 */
export const arraySchemaBodyParityFacetSpliceTest118863Plugin: SitePlugin<ArraySchemaBodyParityFacetSpliceTest118863Payload, ArraySchemaBodyParityFacetSpliceTest118863Response> = {
  meta: {
    siteId: "array-schema-body-parity-facet-splice-test-118863",
    bodySchema: ArraySchemaBodyParityFacetSpliceTest118863PayloadSchema,
    responseSchema: ArraySchemaBodyParityFacetSpliceTest118863ResponseSchema,
    defaultBaseUrl: "https://www.array-schema-body-parity-facet-splice-fixture.example.com",
    // multipart is required whenever the flow itself uploads a file
    // (hasMultipartStep), OR this is a job-application submission flow
    // (usesApplicantContactSchema) since basePayloadSchemaExpr requires a
    // real Resume Buffer via ApplicantContactSchema regardless of whether
    // the recorded browser flow contained an upload step, OR the payload
    // has a non-scalar discoveredStructuredKeys field (payloadNeedsMultipart),
    // since the multipart wire format is what makes that field's
    // JSON-stringified encoding parseable.
    apiVersion: "1.0.0",
    multipart: true,
  },

  /** Hot path: direct HTTP — no browser, no LLM tokens. */
  async executeHttp(
    payload: ArraySchemaBodyParityFacetSpliceTest118863Payload,
    _context: SitePluginContext
  ): Promise<SitePluginResult<ArraySchemaBodyParityFacetSpliceTest118863Response>> {
    // TODO: unbound captured literal(s) — verify these carry caller data, not the recon capture's: 0, 2, 3, 1, storeRegion
    await httpClient(`${payload.BaseUrl}/shop/query-a/`, {
      method: "POST",
      headers: { "Origin": `${payload.BaseUrl}`, "Referer": `${payload.BaseUrl}/` }, body: `{"ordering":[{"criteria":"price","order":"ASC","region":"MI"},{"criteria":"${payload.CategoryFacet};kind=slug","order":"ASC","region":"MI"}],"tags":${JSON.stringify(["a;kind=slug", `${payload.CategoryFacet};kind=slug`, "b;kind=slug"])}}`,
      schema: z.object({
  ok: z.boolean(),
}).loose(),
    });

    await httpClient(`${payload.BaseUrl}/shop/query-b/`, {
      method: "POST",
      headers: { "Origin": `${payload.BaseUrl}`, "Referer": `${payload.BaseUrl}/` }, body: `{"ordering":[{"criteria":"price","order":"ASC","region":"MI"},{"criteria":"${payload.CategoryFacet};kind=slug","order":"ASC","region":"MI"}],"tags":${JSON.stringify(["a;kind=slug", `${payload.CategoryFacet};kind=slug`, ...(payload.BrandFacet ? [`${payload.BrandFacet};kind=slug`] : []), "b;kind=slug"])}}`,
      schema: z.object({
  ok: z.boolean(),
}).loose(),
    });

    await httpClient(`${payload.BaseUrl}/shop/query-c/`, {
      method: "POST",
      headers: { "Origin": `${payload.BaseUrl}`, "Referer": `${payload.BaseUrl}/` }, body: `{"tags":${JSON.stringify([...(payload.BrandFacet ? [`${payload.BrandFacet};kind=slug`] : []), "winter-2026;kind=slug", `${payload.CategoryFacet};kind=slug`])}}`,
      schema: z.object({
  ok: z.boolean(),
}).loose(),
    });

    const r3 = (await httpClient(`${payload.BaseUrl}/shop/query-d/`, {
      method: "POST",
      headers: { "Origin": `${payload.BaseUrl}`, "Referer": `${payload.BaseUrl}/` }, body: `{"tags":${JSON.stringify([`${payload.CategoryFacet};kind=slug`, ...(payload.BrandFacet ? [`${payload.BrandFacet};kind=slug`] : [])])},"page":${payload.page},"storeRegion":${JSON.stringify(payload.RegionFacet ?? "regionx-retail-7003")}}`,
      schema: z.object({
  ok: z.boolean(),
}).loose(),
    })) as Record<string, unknown>;

    return { data: r3 as unknown as ArraySchemaBodyParityFacetSpliceTest118863Response };
  },

  /** Browser fallback: Stagehand + Steel — invoked only when hot path fails. */
  async execute(
    payload: ArraySchemaBodyParityFacetSpliceTest118863Payload,
    session: BrowserSession,
    context: SitePluginContext
  ): Promise<SitePluginResult<ArraySchemaBodyParityFacetSpliceTest118863Response>> {
    const raw = await runArraySchemaBodyParityFacetSpliceTest118863BrowserFlow(session.stagehand, context.baseUrl, payload, session.sessionProxy ?? null);
    return { data: raw as ArraySchemaBodyParityFacetSpliceTest118863Response };
  },
};

// Out-of-tree loader resolves `m.plugin ?? m.default ?? m` — this named
// alias is what BARNACLE_PLUGINS finds; without it the loader would fall
// through to `m.default` (the response schema above) and 404 at runtime.
export { arraySchemaBodyParityFacetSpliceTest118863Plugin as plugin };
