/**
 * Generated by recon-generate.ts.
 * Build this package, then point BARNACLE_PLUGINS at the compiled module —
 * no core edits required:
 *
 *   BARNACLE_PLUGINS=./dist/sites/array-schema-body-parity-facet-splice-test-118863/index.js pnpm start
 *
 * The loader resolves `m.plugin ?? m.default ?? m` — the `plugin` alias
 * below is what it finds.
 */

export { arraySchemaBodyParityFacetSpliceTest118863Plugin, arraySchemaBodyParityFacetSpliceTest118863Plugin as plugin } from "@/sites/array-schema-body-parity-facet-splice-test-118863/contract";
