/**
 * Generated by recon-generate.ts — review before shipping.
 */

import Bottleneck from "bottleneck";
import { z } from "zod/v4";

import { createHttpClient } from "@enricai/barnacle/scraper/http-client";
import type { BrowserSession } from "@enricai/barnacle/scraper/session";
import type { SitePlugin, SitePluginContext, SitePluginResult } from "@enricai/barnacle/site-plugin";
import { runFallbackDomainMinorityGraphqlSubdomainRestClassificationE2eTest118955BrowserFlow } from "@/sites/fallback-domain-minority-graphql-subdomain-rest-classification-e2e-test-118955/flows/browser-flow";

const BASE_HEADERS: Record<string, string> = {
  "Content-Type": "application/json",
  Accept: "application/json, */*",
  Origin: "https://www.orders-rest-fixture.example.net",
  Referer: "https://www.orders-rest-fixture.example.net/",
  "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
};

// Safe ceiling: 5 rps — DEFAULT (no rate-limit probe data; run recon:http).
const limiter = new Bottleneck({ minTime: 200 });

export const FallbackDomainMinorityGraphqlSubdomainRestClassificationE2eTest118955ResponseSchema = z.object({
  items: z.array(z.object({
    id: z.string(),
    name: z.string(),
  }).loose()),
}).loose();

export type FallbackDomainMinorityGraphqlSubdomainRestClassificationE2eTest118955Response = z.infer<typeof FallbackDomainMinorityGraphqlSubdomainRestClassificationE2eTest118955ResponseSchema>;

export default FallbackDomainMinorityGraphqlSubdomainRestClassificationE2eTest118955ResponseSchema;

const FallbackDomainMinorityGraphqlSubdomainRestClassificationE2eTest118955PayloadSchema = z.object({
  query: z.string().min(1),
});

export type FallbackDomainMinorityGraphqlSubdomainRestClassificationE2eTest118955Payload = z.infer<typeof FallbackDomainMinorityGraphqlSubdomainRestClassificationE2eTest118955PayloadSchema>;

const httpClient = createHttpClient({ schema: FallbackDomainMinorityGraphqlSubdomainRestClassificationE2eTest118955ResponseSchema, bottleneck: limiter, baseHeaders: BASE_HEADERS });

/**
 * Plugin for fallback-domain-minority-graphql-subdomain-rest-classification-e2e-test-118955. Tries the direct-HTTP hot path first; falls back to
 * Stagehand automatically on schema drift or bot challenge.
 */
export const fallbackDomainMinorityGraphqlSubdomainRestClassificationE2eTest118955Plugin: SitePlugin<FallbackDomainMinorityGraphqlSubdomainRestClassificationE2eTest118955Payload, FallbackDomainMinorityGraphqlSubdomainRestClassificationE2eTest118955Response> = {
  meta: {
    siteId: "fallback-domain-minority-graphql-subdomain-rest-classification-e2e-test-118955",
    bodySchema: FallbackDomainMinorityGraphqlSubdomainRestClassificationE2eTest118955PayloadSchema,
    responseSchema: FallbackDomainMinorityGraphqlSubdomainRestClassificationE2eTest118955ResponseSchema,
    defaultBaseUrl: "https://www.orders-rest-fixture.example.net",
    apiVersion: "1.0.0",
  },

  /** Hot path: direct HTTP — no browser, no LLM tokens. */
  async executeHttp(
    payload: FallbackDomainMinorityGraphqlSubdomainRestClassificationE2eTest118955Payload,
    context: SitePluginContext
  ): Promise<SitePluginResult<FallbackDomainMinorityGraphqlSubdomainRestClassificationE2eTest118955Response>> {
    const data = await httpClient(`${context.baseUrl}/api/orders/search`, {
      method: "POST",
      body: JSON.stringify({ query: payload.query }),
    });
    return { data };
  },

  /** Browser fallback: Stagehand + Steel — invoked only when hot path fails. */
  async execute(
    payload: FallbackDomainMinorityGraphqlSubdomainRestClassificationE2eTest118955Payload,
    session: BrowserSession,
    context: SitePluginContext
  ): Promise<SitePluginResult<FallbackDomainMinorityGraphqlSubdomainRestClassificationE2eTest118955Response>> {
    const raw = await runFallbackDomainMinorityGraphqlSubdomainRestClassificationE2eTest118955BrowserFlow(session.stagehand, context.baseUrl, payload, session.sessionProxy ?? null);
    return { data: raw as FallbackDomainMinorityGraphqlSubdomainRestClassificationE2eTest118955Response };
  },
};

// Out-of-tree loader resolves `m.plugin ?? m.default ?? m` — this named
// alias is what BARNACLE_PLUGINS finds; without it the loader would fall
// through to `m.default` (the response schema above) and 404 at runtime.
export { fallbackDomainMinorityGraphqlSubdomainRestClassificationE2eTest118955Plugin as plugin };
