/**
 * Generated by recon-generate.ts.
 * Build this package, then point BARNACLE_PLUGINS at the compiled module —
 * no core edits required:
 *
 *   BARNACLE_PLUGINS=./dist/sites/fallback-domain-minority-graphql-subdomain-rest-classification-e2e-test-118955/index.js pnpm start
 *
 * The loader resolves `m.plugin ?? m.default ?? m` — the `plugin` alias
 * below is what it finds.
 */

export { fallbackDomainMinorityGraphqlSubdomainRestClassificationE2eTest118955Plugin, fallbackDomainMinorityGraphqlSubdomainRestClassificationE2eTest118955Plugin as plugin } from "@/sites/fallback-domain-minority-graphql-subdomain-rest-classification-e2e-test-118955/contract";
