/**
 * Generated by recon-generate.ts — review before shipping.
 */

import Bottleneck from "bottleneck";
import { z } from "zod/v4";

import { createHttpClient } from "@enricai/barnacle/scraper/http-client";
import type { BrowserSession } from "@enricai/barnacle/scraper/session";
import type { SitePlugin, SitePluginContext, SitePluginResult } from "@enricai/barnacle/site-plugin";
import { runReportScaleRegression11249E2eTest15615BrowserFlow } from "@/sites/report-scale-regression-1-12-49-e2e-test-15615/flows/browser-flow";

const BASE_HEADERS: Record<string, string> = {
  "Content-Type": "application/json",
  Accept: "application/json, */*",
  Origin: "https://www.own-backend-1-12-49-report-scale-regression-fixture.example.com",
  Referer: "https://www.own-backend-1-12-49-report-scale-regression-fixture.example.com/",
  "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
};

// Safe ceiling: 5 rps — DEFAULT (no rate-limit probe data; run recon:http).
const limiter = new Bottleneck({ minTime: 200 });

export const ReportScaleRegression11249E2eTest15615ResponseSchema = z.object({
  variants: z.array(z.object({
    variantId: z.string(),
    drillAttribute0: z.string(),
    drillAttribute1: z.string(),
    drillAttribute2: z.string(),
    drillAttribute3: z.string(),
    drillAttribute4: z.string(),
    drillAttribute5: z.string(),
    drillAttribute6: z.string(),
    drillAttribute7: z.string(),
    drillAttribute8: z.string(),
    drillAttribute9: z.string(),
    drillAttribute10: z.string(),
    drillAttribute11: z.string(),
    drillAttribute12: z.string(),
    drillAttribute13: z.string(),
    drillAttribute14: z.string(),
    drillAttribute15: z.string(),
    drillAttribute16: z.string(),
    drillAttribute17: z.string(),
    drillAttribute18: z.string(),
    drillAttribute19: z.string(),
    drillAttribute20: z.string(),
    drillAttribute21: z.string(),
    drillAttribute22: z.string(),
    drillAttribute23: z.string(),
    drillAttribute24: z.string(),
    drillAttribute25: z.string(),
    drillAttribute26: z.string(),
    drillAttribute27: z.string(),
    drillAttribute28: z.string(),
    drillAttribute29: z.string(),
    drillAttribute30: z.string(),
    drillAttribute31: z.string(),
    drillAttribute32: z.string(),
    drillAttribute33: z.string(),
    drillAttribute34: z.string(),
    drillAttribute35: z.string(),
    drillAttribute36: z.string(),
    drillAttribute37: z.string(),
    drillAttribute38: z.string(),
    drillAttribute39: z.string(),
  }).loose()),
  conversionRate: z.number(),
}).loose();

export type ReportScaleRegression11249E2eTest15615Response = z.infer<typeof ReportScaleRegression11249E2eTest15615ResponseSchema>;

export default ReportScaleRegression11249E2eTest15615ResponseSchema;

const ReportScaleRegression11249E2eTest15615PayloadSchema = z.object({
  query: z.string().min(1),
});

export type ReportScaleRegression11249E2eTest15615Payload = z.infer<typeof ReportScaleRegression11249E2eTest15615PayloadSchema>;

const httpClient = createHttpClient({ schema: ReportScaleRegression11249E2eTest15615ResponseSchema, bottleneck: limiter, baseHeaders: BASE_HEADERS });

/**
 * Plugin for report-scale-regression-1-12-49-e2e-test-15615. Tries the direct-HTTP hot path first; falls back to
 * Stagehand automatically on schema drift or bot challenge.
 */
export const reportScaleRegression11249E2eTest15615Plugin: SitePlugin<ReportScaleRegression11249E2eTest15615Payload, ReportScaleRegression11249E2eTest15615Response> = {
  meta: {
    siteId: "report-scale-regression-1-12-49-e2e-test-15615",
    bodySchema: ReportScaleRegression11249E2eTest15615PayloadSchema,
    responseSchema: ReportScaleRegression11249E2eTest15615ResponseSchema,
    defaultBaseUrl: "https://www.own-backend-1-12-49-report-scale-regression-fixture.example.com",
    apiVersion: "1.0.0",
  },

  /** Hot path: direct HTTP — no browser, no LLM tokens. */
  async executeHttp(
    payload: ReportScaleRegression11249E2eTest15615Payload,
    context: SitePluginContext
  ): Promise<SitePluginResult<ReportScaleRegression11249E2eTest15615Response>> {
    const data = await httpClient(`${context.baseUrl}/directory-record-drill/`, {
      method: "POST",
      body: JSON.stringify({ query: payload.query }),
    });
    return { data };
  },

  /** Browser fallback: Stagehand + Steel — invoked only when hot path fails. */
  async execute(
    payload: ReportScaleRegression11249E2eTest15615Payload,
    session: BrowserSession,
    context: SitePluginContext
  ): Promise<SitePluginResult<ReportScaleRegression11249E2eTest15615Response>> {
    const raw = await runReportScaleRegression11249E2eTest15615BrowserFlow(session.stagehand, context.baseUrl, payload, session.sessionProxy ?? null);
    return { data: raw as ReportScaleRegression11249E2eTest15615Response };
  },
};

// Out-of-tree loader resolves `m.plugin ?? m.default ?? m` — this named
// alias is what BARNACLE_PLUGINS finds; without it the loader would fall
// through to `m.default` (the response schema above) and 404 at runtime.
export { reportScaleRegression11249E2eTest15615Plugin as plugin };
