/**
 * Generated by recon-generate.ts.
 * Build this package, then point BARNACLE_PLUGINS at the compiled module —
 * no core edits required:
 *
 *   BARNACLE_PLUGINS=./dist/sites/report-scale-regression-1-12-49-e2e-test-15615/index.js pnpm start
 *
 * The loader resolves `m.plugin ?? m.default ?? m` — the `plugin` alias
 * below is what it finds.
 */

export { reportScaleRegression11249E2eTest15615Plugin, reportScaleRegression11249E2eTest15615Plugin as plugin } from "@/sites/report-scale-regression-1-12-49-e2e-test-15615/contract";
