/**
 * Generated by recon-generate.ts — review before shipping.
 */

import Bottleneck from "bottleneck";
import { z } from "zod/v4";

import { createGraphqlClient } from "@enricai/barnacle/scraper/graphql-client";
import type { BrowserSession } from "@enricai/barnacle/scraper/session";
import type { SitePlugin, SitePluginContext, SitePluginResult } from "@enricai/barnacle/site-plugin";
import { runGqlNonjoinUnresolvableRun23247BrowserFlow } from "@/sites/gql-nonjoin-unresolvable-run23247/flows/browser-flow";

const BASE_HEADERS: Record<string, string> = {
  "Content-Type": "application/json",
  Accept: "application/json, */*",
  Origin: "https://api.example.com",
  Referer: "https://api.example.com/",
  "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
};

// Safe ceiling: 5 rps — DEFAULT (no rate-limit probe data; run recon:http).
const limiter = new Bottleneck({ minTime: 200 });

export const GqlNonjoinUnresolvableRun23247ResponseSchema = z.object({
  companySearch: z.object({
    companies: z.array(z.object({
      id: z.string(),
      packageCode: z.string(),
      title: z.string(),
    }).loose()),
  }).loose(),
}).loose();

export type GqlNonjoinUnresolvableRun23247Response = z.infer<typeof GqlNonjoinUnresolvableRun23247ResponseSchema>;

export default GqlNonjoinUnresolvableRun23247ResponseSchema;

const GqlNonjoinUnresolvableRun23247PayloadSchema = z.object({
  query: z.string().min(1),
});

export type GqlNonjoinUnresolvableRun23247Payload = z.infer<typeof GqlNonjoinUnresolvableRun23247PayloadSchema>;

// Lifted verbatim from recon capture. The adjacent response schema is drift-tolerant by construction (dropped __typename, .loose() objects), so this query text is not hand-trimmed.
const GQLNONJOINUNRESOLVABLERUN23247_QUERY = `query companySearch { companySearch { companies { id packageCode title } } }`;

type GqlFn = (operationName: string, query: string, variables: Record<string, unknown>) => Promise<GqlNonjoinUnresolvableRun23247Response>;

const gqlCache = new Map<string, GqlFn>();

function getGql(baseUrl: string): GqlFn {
  let client = gqlCache.get(baseUrl);
  if (!client) {
    client = createGraphqlClient({
      schema: GqlNonjoinUnresolvableRun23247ResponseSchema,
      bottleneck: limiter,
      baseHeaders: BASE_HEADERS,
      endpoint: `${baseUrl}/graphql`,
    });
    gqlCache.set(baseUrl, client);
  }
  return client;
}

/**
 * Plugin for gql-nonjoin-unresolvable-run23247. Tries the direct-HTTP hot path first; falls back to
 * Stagehand automatically on schema drift or bot challenge.
 */
export const gqlNonjoinUnresolvableRun23247Plugin: SitePlugin<GqlNonjoinUnresolvableRun23247Payload, GqlNonjoinUnresolvableRun23247Response> = {
  meta: {
    siteId: "gql-nonjoin-unresolvable-run23247",
    bodySchema: GqlNonjoinUnresolvableRun23247PayloadSchema,
    responseSchema: GqlNonjoinUnresolvableRun23247ResponseSchema,
    defaultBaseUrl: "https://api.example.com",
    apiVersion: "1.0.0",
  },

  /** Hot path: direct HTTP — no browser, no LLM tokens. */
  async executeHttp(
    _payload: GqlNonjoinUnresolvableRun23247Payload,
    context: SitePluginContext
  ): Promise<SitePluginResult<GqlNonjoinUnresolvableRun23247Response>> {
    const data = await getGql(context.baseUrl)("companySearch", GQLNONJOINUNRESOLVABLERUN23247_QUERY, {});
    return { data };
  },

  /** Browser fallback: Stagehand + Steel — invoked only when hot path fails. */
  async execute(
    payload: GqlNonjoinUnresolvableRun23247Payload,
    session: BrowserSession,
    context: SitePluginContext
  ): Promise<SitePluginResult<GqlNonjoinUnresolvableRun23247Response>> {
    const raw = await runGqlNonjoinUnresolvableRun23247BrowserFlow(session.stagehand, context.baseUrl, payload, session.sessionProxy ?? null);
    return { data: raw as GqlNonjoinUnresolvableRun23247Response };
  },
};

// Out-of-tree loader resolves `m.plugin ?? m.default ?? m` — this named
// alias is what BARNACLE_PLUGINS finds; without it the loader would fall
// through to `m.default` (the response schema above) and 404 at runtime.
export { gqlNonjoinUnresolvableRun23247Plugin as plugin };
