/**
 * Generated by recon-generate.ts.
 * Build this package, then point BARNACLE_PLUGINS at the compiled module —
 * no core edits required:
 *
 *   BARNACLE_PLUGINS=./dist/sites/gql-nonjoin-unresolvable-run23247/index.js pnpm start
 *
 * The loader resolves `m.plugin ?? m.default ?? m` — the `plugin` alias
 * below is what it finds.
 */

export { gqlNonjoinUnresolvableRun23247Plugin, gqlNonjoinUnresolvableRun23247Plugin as plugin } from "@/sites/gql-nonjoin-unresolvable-run23247/contract";
